### ISSUE TITLE
Ozmo 950 SpotArea ?

### ISSUE THREAD

**Issue by heiko1988** [mrbungle64/ecovacs-deebot.js#13]
Leider bekomme ich es nicht hin, den Ozmo 950 mit dem SpotArea zu starten.

vacbot.run("SpotArea", "spot_area", "start", "3");

ist doch so Richtig geschrieben?
Kann mir bitte Jemand ein Beispiel Geben?

Danke :)

**Comment by mrbungle64** [comment]
Hallo @heiko1988 

da ist leider in Fehler in der Readme - das geht folgendermaßen:

```javascript
vacbot.run("SpotArea", "start", "3");
```

**Comment by heiko1988** [comment]
Hi,

Danke für das Schnelle Feedback und Jetzt Funktioniert es auch.


Ein Weitere  Schreibt gerade ein Modul Für Pimatic.
https://forum.pimatic.org/topic/4824/robotic-vacuum-ecovacs-deebot-ozmo-950-and-etc

Vielen Dank für die Lib. :)

**Comment by mrbungle64** [comment]
@heiko1988 

Freut mich, dass es nun funktioniert und danke für den Hinweis :+1:
