### ISSUE TITLE
Cleaning Preference

### ISSUE THREAD

**Issue by m1k3f15h** [mrbungle64/ecovacs-deebot.js#133]
### The feature request

In the Ecovacs App you can choose between 2 different Cleaning Preferences:
View & Edit
Customize
![Screenshot_20220217-082552__01](https://user-images.githubusercontent.com/26365771/154448433-4e72a7a3-be1a-4875-bc90-a8e726830c9c.jpg)

It would be nice to get/set this preference with your node-package.

### Which model do you own?

Deebot T9 series

**Comment by mrbungle64** [comment]
@m1k3f15h 

`GetCleaningPreference` and `SetCleaningPreference` commands are implemented now
