### ISSUE TITLE
Basic usage question

### ISSUE THREAD

**Issue by maltejahn** [mrbungle64/ecovacs-deebot.js#153]
Hi,

i am trying to use this library, but i dont know if i am just to dumb to use it the right way.

I started using the app.js example and started it with node app.js. The Problem is, the program never end/exit

```
Devices: [{"did":"E00xxxxxxxxxxx","name":"E00xxxxxxx","class":"115","resource":"atom","nick":null,"company":"eco-legacy","deviceName":"DEEBOT OZMO/PRO 930 Series","icon":"https://portal-ww.ecouser.net/api/pim/file/get/5cf7xxxxx","ota":true,"UILogicId":"DR_930G","materialNo":"110-1602-0101","pid":"5bb","product_category":"DEEBOT","model":"DR930","updateInfo":{"needUpdate":false,"changeLog":""},"status":2,"deviceNumber":0}]

vacbot ready

Clean status: stop
Charge status: charging
```

I am also wondering why i dont get a battery charging level. Is there a way to debug this? Also, sometimes even these messages (Clean status, Charge status) arent showing up.

I use FHEM as my home automation software. There i can call a js script, like `cleankitchen {system("nodejs /home/pi/ecovacs-deebot.js/fhemscripts/cleankitchen.js");}`
So i would like to build several scripts for each clean task (or for retrieving status information)

This here starts cleaning and exits the script using disconnect - but i doubt thats the intended use

```js
const ecovacsDeebot = require('./../index');
const tools = require('./tools');
const EcoVacsAPI = ecovacsDeebot.EcoVacsAPI;
const nodeMachineId = require('node-machine-id');

let settingsFile = tools.getSettingsFile();

const account_id = settingsFile.ACCOUNT_ID;
const password = settingsFile.PASSWORD;
const countryCode = settingsFile.COUNTRY_CODE;
const deviceNumber = settingsFile.DEVICE_NUMBER;

// The password_hash is an md5 hash of your Ecovacs password.
const password_hash = EcoVacsAPI.md5(password);
// You need to provide a device ID uniquely identifying the machine you're using to connect
const device_id = EcoVacsAPI.getDeviceId(nodeMachineId.machineIdSync(), deviceNumber);

let api = new EcoVacsAPI(device_id, countryCode);

// This logs you in through the HTTP API and retrieves the required
// access tokens from the server side. This allows you to requests
// the devices linked to your account to prepare connectivity to your vacuum.
api.connect(account_id, password_hash).then(() => {

  api.devices().then((devices) => {
    console.log('Devices:', JSON.stringify(devices));

    let vacuum = devices[deviceNumber];
    let vacbot = api.getVacBot(api.uid, EcoVacsAPI.REALM, api.resource, api.user_access_token, vacuum, api.getContinent());

    // Once the session has started the bot will fire a "ready" event.
    // At this point you can request information from your vacuum or send actions to it.
    vacbot.on('ready', (event) => {

      console.log('\nvacbot ready\n');

      vacbot.run('BatteryState');
      vacbot.run('GetCleanState');
      vacbot.run('GetChargeState');

      vacbot.on('BatteryInfo', (battery) => {
        console.log('Battery level: ' + Math.round(battery));
      });
      vacbot.on('CleanReport', (value) => {
        console.log("Clean status: " + value);
      });
      vacbot.on('ChargeState', (value) => {
        console.log("Charge status: " + value);
      });
           const areas = '0'; // Example values
            vacbot.spotArea(areas); // version >= 0.6.2
    });
    vacbot.connect();
vacbot.disconnect();


        //
        // Catch ctrl-c to exit program
        //
        process.on('SIGINT', function () {
            console.log('\nGracefully shutting down from SIGINT (Ctrl+C)');
            disconnect();
        });

        function disconnect() {
            try {
                vacbot.disconnect();
            } catch (e) {
                console.log('Failure in disconnecting: ', e.message);
            }
            console.log('Exiting...');
            process.exit();
        }

  });
}).catch((e) => {
  console.error(`Failure in connecting: ${e.message}`);
});
```

**Comment by mrbungle64** [comment]
@maltejahn 

You call `disconnect()` immediately after the calling `connect()`.
That's the reason why don't receive all events.

```js
vacbot.connect();
vacbot.disconnect();
```

By the way, the library is not actually designed for scripting.
Some functions will (maybe) work properly - some not.

**Comment by maltejahn** [comment]
Hi,

sorry for being late. But i havent done that much the last few days. Btw. its a Deebot 930.
The Bot can be reached by the Deebot App, so WiFi should be fine. 

Maybe you misunderstood. If I run app.js - unchanged (of course with login data) -  it never ends. 

`
Devices: [{"did":"E00xxxxxxxxxxx","name":"E00xxxxxxx","class":"115","resource":"atom","nick":null,"company":"eco-legacy","deviceName":"DEEBOT OZMO/PRO 930 Series","icon":"https://portal-ww.ecouser.net/api/pim/file/get/5cf7xxxxx","ota":true,"UILogicId":"DR_930G","materialNo":"110-1602-0101","pid":"5bb","product_category":"DEEBOT","model":"DR930","updateInfo":{"needUpdate":false,"changeLog":""},"status":2,"deviceNumber":0}]

vacbot ready

Clean status: stop
Charge status: charging
`

I would have expected that i get a "BatteryState" message. But sometimes even the Clean Status is missing. And, it doenst stop.

My goal is to start/stop/get some basic information from the bot to my FHEM Home automation. The easiest thing to get data is a json mqtt string. 
I started with node red and it connects and gets data. But i hoped i can avoid node red as I dont have any need for thos (oof course till now...).

But after a few minutes I already got some mqtt messages from the cleaning bot - probably the way to go

**Comment by mrbungle64** [comment]
@maltejahn 

> I would have expected that i get a "BatteryState" message

There was a bug in the app.js file related to the battery charging level. I already fixed it.

> And, it doenst stop

What do you mean?

**Comment by maltejahn** [comment]
Hi,

my main "problem" was that I thought to tuse the library like a script. Start + Do a command + End

I now use it with Red node, my FHEM "smart" home sends the command using mqtt, and it receives the messages using mqtt. 

So thats probably the easiest way.

Thanks
