### ISSUE TITLE
GetChargerPos doesn't trigger any event in response

### ISSUE THREAD

**Issue by Smilebags** [mrbungle64/ecovacs-deebot.js#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

GetChargerPos doesn't trigger any event to be returned.

When I run the following code (where deviceConnection is the return value of `EcoVacsAPI.getVacBot`), resolve is called with an object.
```
this.deviceConnection.run('GetPosition');
this.deviceConnection.on('Position', (event) => {
  resolve(event);
});
```

When I do the same thing, but instead with `GetChargerPos`, no event is fired in response.
```
this.deviceConnection.run('GetChargerPos');
this.deviceConnection.on('ChargingPosition', (event) => {
  resolve(event);
});
```
I have checked that it's not just the wrong event I'm listening for, since I have this code also running:
```
this.deviceConnection.on('messageReceived', e => console.log('MESSAGE_RECEIVED', e));
```

Is this a bug? Am I missing something, or is the Deebot API just not working as expected?

### With which model does the problem occur?

Deebot T8 series

### From which source you have installed the adapter?

npm

### Version of the ecovacs-deebot.js library

0.7.2

### Version of Node.js

v16.13..1

### Operating system

Windows

**Comment by mrbungle64** [comment]
Hi @Smilebags 

I just checked and for me it's still working as expected.
I don't own a Deebot T8 but it should also work with this model.

A possible explanation is that the event is fired only once if the position of the load has not changed.
Please check if the event is fired once after startup.

**Comment by Smilebags** [comment]
Hi, I've included a log of my application with NODE_ENV=dev to show the debug logs. I am calling `GetChargerPos` in this program after receiving the `ready` event. 

```
$ NODE_ENV=dev node ./dist/index.js
[EcovacsAPI] Setting up EcovacsAPI
[EcovacsAPI] Calling main api user/login with {"account":"******","password":"******"}
[EcoVacsAPI] callUserAuthApi calling https://gl-au-api.ecovacs.
com/v1/private/au/EN/******/global_e/
1.6.3/google_play/1/user/login
[EcoVacsAPI] callUserAuthApi config account=******&password=******&authTimespan=1650702000166
&authTimeZone=GMT-8&authAppkey=******&authSign=******
[EcoVacsAPI] callUserAuthApi data: {"code":"0000","msg":"操作成
功","time":1650702004083,"data":{"uid":"******","accessToken":"******","userName":"EAWNTTP5","email":"******","mobile":null,"isNew":null,"loginName":"christophe
r.cook@outlook.com.au","ucUid":"******"},"success":true}
[EcovacsAPI] Calling main api user/getAuthCode with {"uid":"******","accessToken":"******"}
[EcoVacsAPI] callUserAuthApi calling https://gl-au-openapi.ecov
acs.com/v1/global/auth/getAuthCode
[EcoVacsAPI] callUserAuthApi config uid=******&accessToken=******&bizType=ECOVACS_IOT&deviceId=******&authTimespan=1650702001902&authAppkey=1520391491841&authS
ign=******
[EcoVacsAPI] callUserAuthApi data: {"code":"0000","msg":"操作成
功","time":1650702006044,"data":{"authCode":"GLOBAL_APP_ECOVACS
_IOT_******","ecovacsUid":"******"},"success":true}        
[EcovacsAPI] calling user api loginByItToken with {"edition":"E
COGLOBLE","userId":"******","token":"******","realm":"ecouser.net","resource":"df261dee","org":"ECO
WW","last":"","country":"AU"}
[EcoVacsAPI] continent ww
[EcoVacsAPI] Calling https://portal-ww.ecouser.net/api/users/us
er.do
[EcovacsAPI] got {"todo":"result","result":"ok","userId":"fg5eg
wp5cfeb56a3","resource":"df261dee","token":"******","last":60480000
0}
[EcovacsAPI] EcovacsAPI connection complete
[EcovacsAPI] calling user api GetDeviceList with {"userid":"******","auth":{"with":"users","userid":"******","realm":"ecouser.net","token":"******","resource":"df261dee"}}  
,"model":"OT8G","updateInfo":{"needUpdate":false,"changeLog":""},"status":1,"offmap":true}]}
vacBot_950type identified
[EcovacsMQTT] Connecting as ******@ecouser to mqtts://mq-ww.ecouser.net:8883
[EcovacsMQTT] client connected
iot/atr/+/dce01503-1669-4934-b65b-eb8002e29ecb/h18jkh/tI5S/j   
[EcovacsMQTT] Subscribed to atr channel
[VacBot] Ready event!
[EcovacsMQTT] Received ready event
```

To me it looks like my call of `run('GetChargerPos')` isn't doing anything at all.

**Comment by mrbungle64** [comment]
@Smilebags 

I wasn't aware of it yet either, but you need to run also `GetPosition` to get a response for `GetChargerPos`.

```js
this.deviceConnection.run('GetPosition');
this.deviceConnection.run('GetChargerPos');
```

I've generally handled it that way so far, so I wasn't aware of it yet 😃

**Comment by Smilebags** [comment]
That's great to know, thanks!

To confirm your previous point: GetChargerPos will not cause a new event if the charger position has not changed since the last call during the current session, is that correct? Does that suggest I should be caching the result of this value?

**Comment by Smilebags** [comment]
Also, can confirm that adding the additional call to 'GetPosition' enabled GetChargerPos to trigger the relevant event, thanks for looking into it!

I'm curious whether there is a place for documentation like this in this repo, if so I am happy to make a PR to update it with this knowledge. A mapping of Command > expected response event is something else I've been wishing existed, I'm happy to start it off if you think it would be helpful.

**Comment by mrbungle64** [comment]
@Smilebags 

> To confirm your previous point: GetChargerPos will not cause a new event if the charger position has not changed since the last call during the current session, is that correct? Does that suggest I should be caching the result of this value?

Yes, that's correct. But I'll also think about how I can improve that bevaviour.
Feel free to make a suggestion for improvement.

**Comment by Smilebags** [comment]
Thanks, this seems to be resolved now. I'll see whether I have some meaningful suggestions for improvement.
