### ISSUE TITLE
Question: Koordinaten herausfinden 

### ISSUE THREAD

**Issue by heiko1988** [mrbungle64/ecovacs-deebot.js#18]
Hi,

Wie finde ich den genauen Standort für 
Eine bereichs Reinigung

Also die 4 Variablen in dem. Bereich wo er reinigen soll. 

Kann ich den deebot einfach in alle 4 Ecken stellen und die Koordinaten abrufen, wahrscheinlich denke ich da zu einfach

**Comment by boriswerner** [comment]
Das könnte tatsächlich so funktionieren, hat aber glaube ich noch niemand wirklich getestet (du könntest also Pionierarbeit leisten :-) 
Es gibt da noch viel Potenzial, ist aber auch deutlich komplexer als die anderen Reinigungsmodi.

**Comment by mrbungle64** [comment]
@heiko1988 @boriswerner 

Ich habe das bisher so gemacht, dass ich eine entsprechende Bereichsreinigung über die Mobile App gestartet habe und dann sind die 4 Werte im Log der Beispiel App zu finden:

```
NODE_ENV=dev node app2.js | grep -E 'SpotArea|spotArea|customArea'
```

Beim Ozmo 950 sollte es mit "customArea" gehen - bin mir aber nicht sicher.

**Comment by heiko1988** [comment]
Gerne doch,
Bin nicht so ganz bewandert, in der Materie mit Programmierungen. 
Kann a weng html, php aber Dann hört es auch schon wieder auf ;) 

Kann man die aktuelle Position auslesen? 
Oder aus der App extrahieren? 

Dann könnte ich den in alle 4 Ecken stellen und jeweils ein relocate ausführen und dann die Position wieder auslesen.

**Comment by heiko1988** [comment]
@mrbungle64 danke für den tip, das funktioniert schonmal :)

Werde schauen ob ich das mit dem in die 4 Ecken hinstellen und die Daten auslesen hinbekomme

**Comment by boriswerner** [comment]
@heiko1988 den iobroker nutzt du nicht zufällig auch, oder? Da wäre es dann wahrscheinlich einfacher mit dem relocate und der Anzeige der Position.
Aber in der Beispielapp kannst du auch ein relocate absetzen (oder noch einfacher: über die App) und dann auf die Position Message warten. Im grep könntest du onPos oder deebotPos nutzen um zu filtern

**Comment by heiko1988** [comment]
@boriswerner ne nutze Ich nicht Produktiv, habe den mal zum a weng testen gehabt.
Nutze Pimatic.

**Comment by mrbungle64** [comment]
Hi @heiko1988 

können wir den Issue schließen?

**Comment by heiko1988** [comment]
Hi,

Ja kann man zu machen, ist ja in dem Sinne kein Problem, sondern eine Frage. 

Eventuell kann man das in die Dokumentation mit aufnehmen. 

Gruß Heiko
