### ISSUE TITLE
[EcovacsMQTT] failure code: 500

### ISSUE THREAD

**Issue by mrbungle64** [mrbungle64/ecovacs-deebot.js#19]
MQTT based models (non 950) throw `failure code: 500` when press "pause" button using mobile app.

```
[EcovacsMQTT] call failed with {"ret":"fail","errno":500,"debug":"wait for response timed out"}
[EcovacsMQTT] failure code: 500
[EcovacsMQTT] error send_command: failure code: 500
```

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/29#issuecomment-595698807

**Comment by nicoduj** [comment]
I just checked this one, and it seems to work on my side with homebridge plugin under dev using your lib (deebot MQTT OZMO SLIM 10)

**Comment by mrbungle64** [comment]
> I just checked this one, and it seems to work on my side with homebridge plugin under dev using your lib (deebot MQTT OZMO SLIM 10)

Thanks for this information. I guess it's a Deebot 710 related problem.
