### ISSUE TITLE
"ecovacs-deebot.0.control.cleanSpeed" which expects a string.

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ecovacs-deebot.js#22]
Hey

erstmal vielen vielen Dank für eure Mühen. Beim herumprobieren ist mir folgendes augefallen.
warum erwartet der einen string und keine number? sind ja schließlich nur nummerische werte drin.

by the way, es wäre toll überall standardwerte drin zu haben damit man besser skripte schreiben kann zB error - ist leer wenn es keinen fehler gibt vl kann man einfach null oder so als standardwert nehmen.

danke

**Comment by mrbungle64** [comment]
Hi @krobipd 

Deinen Fragen betreffen den ioBroker Adapter, oder? ;)

**Comment by krobipd** [comment]
Schande über mein Haupt 🙈aber erreicht hoffentlich dennoch die richtigen Personen

**Comment by mrbungle64** [comment]
> Schande über mein Haupt aber erreicht hoffentlich dennoch die richtigen Personen

Ja schon, aber Library und Adapter sollten trotzdem getrennt behandelt werden.

Unabhängig davon verstehe ich es aber auch nicht ...

Der State wird als "number" erzeugt und hat einen Wertebereich von `1` bis `4`:

```javascript
...
	name: 'Clean Speed',
	type: 'number',
	...
	'min': 1,
	'max': 4,
	'states': {
	    1: 'silent',
	    2: 'normal',
	    3: 'high',
	    4: 'veryhigh'
	}
...
```

Nur die Auswahl wird nicht als number dargestellt (s. "states")
