### ISSUE TITLE
Are there anyway to connect to the Ecovacs Robot without login?

### ISSUE THREAD

**Issue by lygialiem** [mrbungle64/ecovacs-deebot.js#241]
### The question

Hi Mr.Bungle

First, just wanna thank you for your wonderful libs. I wonder are there anyway to connect to Ecovacs Robot without login? Any opened sockets on this kind of robots to discovery and connect.

Best Regard.

**Comment by mrbungle64** [comment]
@lygialiem 

> First, just wanna thank you for your wonderful libs

Thanks for the feedback 👍🏻 

> I wonder are there anyway to connect to Ecovacs Robot without login? Any opened sockets on this kind of robots to discovery and connect.

Sorry, this library only supports to run Deebot devices using the official Ecovacs login 😉
