### ISSUE TITLE
No "ready" event received

### ISSUE THREAD

**Issue by schaazzz** [mrbungle64/ecovacs-deebot.js#249]
### The question

I have a DEEBOT N8 Pro+ and have just started to explore the library.
When I run app.js, I get the following output and then nothing happens:

`Devices: [{"did":"52db1ed5-32a3-44d1-9f98-8dd366a4b858","name":"E08A14493C09HK1E0479","class":"ifbw08","resource":"cdqB","nick":null,"company":"eco-ng","bindTs":1638652611622,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"},"homeId":"626d061f277e9c3be7ec8de9","homeSort":9999,"deviceName":"DEEBOT N8 PRO+","icon":"https://portal-ww.ecouser.net/api/pim/file/get/61318e07e37c4686071aee67","ota":true,"UILogicId":"DT_8SE_G","materialNo":"110-2008-0901","pid":"5fbc7e18c7260e0008585c8f","product_category":"DEEBOT","model":"N8_PRO_PLUS_WHITE","updateInfo":{"needUpdate":false,"changeLog":""},"status":1,"offmap":true,"deviceNumber":0}]`

I can communicate with the vacuum using the app. I don't know if I'm making some dumb usage mistake or if it's something else. Would appreciate any suggestions on how to proceed.

### Which model do you own?

Deebot N8 series

**Comment by mrbungle64** [comment]
@schaazzz 

If you don't receive "ready" event then you maybe cannot subscribe to the MQTT channel.
Make sure that you can reach mq-eu.ecouser.net:8883 from your machine.

**Comment by schaazzz** [comment]
Thank you for responding so quickly. That was exactly the problem.
I was on my company laptop and the VPN connects by default, once I disconnected from the VPN, it worked fläwlessly.
