### ISSUE TITLE
Compatibility with Deebot 920 , possible?

### ISSUE THREAD

**Issue by scobby** [mrbungle64/ecovacs-deebot.js#25]
Currently i have a issue in the pimatic-deebot plugin, using your libary.

https://github.com/bertreb/pimatic-deebot/issues/3

do you have any idee if this is a bug or just not yet supported?

**Comment by mrbungle64** [comment]
Hi scobby,

the Ozmo 920 model is not supported yet. As far as I know it's simular to Ozmo 950, so we maybe only need to know the "deviceClass" of that model.

Please install the library:

```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

In the file app2.js please modify email and password and then run the file:

```bash
NODE_ENV=dev node app2.js | grep 'class:'
```

If `Failure code 0002` appears please repeat until it's working.

**Comment by scobby** [comment]
**First output was:** 
[EcovacsAPI] Failure code 0002
**Second output:**
root@rasp:/home/pi/developement/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'class:|company:|nick:'
  class: 'vi829v',
  nick: 'Staubsauger',
  company: 'eco-ng',
/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:217
            event = firstChild.attributes.getNamedItem('td').value;
                                          ^

TypeError: Cannot read property 'getNamedItem' of null
    at EcovacsMQTT._command_to_dict (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:217:43)
    at EcovacsMQTT._handle_message_payload (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:202:27)
    at MqttClient.EcovacsMQTT.client.on (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:81:18)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/pi/developement/ecovacs-deebot.js/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/pi/developement/ecovacs-deebot.js/node_modules/readable-stream/lib/_stream_writable.js:417:5)

**Comment by mrbungle64** [comment]
> **First output was:**
> [EcovacsAPI] Failure code 0002
> **Second output:**
> root@rasp:/home/pi/developement/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'class:|company:|nick:'
> class: 'vi829v',
> nick: 'Staubsauger',
> company: 'eco-ng',

ok, I'll update the library later this evening.

**Comment by mrbungle64** [comment]
> **First output was:**
> [EcovacsAPI] Failure code 0002
> **Second output:**
> root@rasp:/home/pi/developement/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'class:|company:|nick:'
> class: 'vi829v',
> nick: 'Staubsauger',
> company: 'eco-ng',
> /home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:217
> event = firstChild.attributes.getNamedItem('td').value;
> ^
> 
> TypeError: Cannot read property 'getNamedItem' of null
> at EcovacsMQTT._command_to_dict (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:217:43)
> at EcovacsMQTT._handle_message_payload (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:202:27)
> at MqttClient.EcovacsMQTT.client.on (/home/pi/developement/ecovacs-deebot.js/library/ecovacsMQTT.js:81:18)
> at MqttClient.emit (events.js:198:13)
> at MqttClient._handlePublish (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:1162:12)
> at MqttClient._handlePacket (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:351:12)
> at work (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:283:12)
> at Writable.writable._write (/home/pi/developement/ecovacs-deebot.js/node_modules/mqtt/lib/client.js:294:5)
> at doWrite (/home/pi/developement/ecovacs-deebot.js/node_modules/readable-stream/lib/_stream_writable.js:428:64)
> at writeOrBuffer (/home/pi/developement/ecovacs-deebot.js/node_modules/readable-stream/lib/_stream_writable.js:417:5)

@scobby
Can you please update to latest GitHub version of the library and give me feedback if it works now?

@boriswerner @bertreb

**Comment by scobby** [comment]
seems to work. after running to command again, deebot has start cleaning.

root@rasp:/home/pi/developement/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'class:|company:|nick:'
  class: 'vi829v',
  nick: 'Staubsauger',
  company: 'eco-ng',

^C

**Comment by scobby** [comment]
Thx you very much!
