### ISSUE TITLE
Waterbox info

### ISSUE THREAD

**Issue by mrbungle64** [mrbungle64/ecovacs-deebot.js#264]
### Discussed in https://github.com/mrbungle64/ecovacs-deebot.js/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **cactusss** December 12, 2022</sup>
I found that since ApiVerion 8.1 the WaterBoxInfo doesn't work anymore, in it returns the waterlevel. But I need to know if (on my T9+) the waterbox is attached. Is there any way to do that in the newer ApiVersions?</div>

**Comment by mrbungle64** [comment]
@cactusss 

There was an issue that the API returned a wrong value while the bot is in sleeping mode, so I decided to emit `WaterBoxInfo` only when not in sleeping mode. The problem is that the bot is switching to sleeping mode very quickly.

I'll have to check it again.

**Comment by cactusss** [comment]
Thanks. Much appreciated!

**Comment by mrbungle64** [comment]
@cactusss 

Should be fixed with version 0.9.1-beta.3

**Comment by cactusss** [comment]
Thank you @mrbungle64 it works again.
