### ISSUE TITLE
CleanReport and CleanSum

### ISSUE THREAD

**Issue by cactusss** [mrbungle64/ecovacs-deebot.js#265]
### The question

You know where I can find any information on how to use the GetCleanLogs and GetCleanSum? the vacbot.on(CleanLogs) vacbot.on(CleanSum) doesn't seem to do anything. Although I'm not sure how to use them and what they should return/display

### Which model do you own?

Deebot T9 series

**Comment by mrbungle64** [comment]
@cactusss 

`vacbot.run('GetCleanLogs');` should work since version 0.9.1-alpha.4
I'm not sure if `vacbot.run('GetCleanSum')` is working for T9 based models (e.g. T9/T10/X1/N8)

**Comment by cactusss** [comment]
You are right, it now work. Now two other questions arose:

1. Where can I get the explanation of the stopReason codes
2. If the type is spotcleaning, is there a way to determine what spot/zone was cleaned?

T.i.a.!

**Comment by mrbungle64** [comment]
@cactusss 

> You are right, it now work. Now two other questions arose:
> 
> 1. Where can I get the explanation of the stopReason codes

I have not really yet looked into that 😉 

> 2. If the type is spotArea, is there a way to determine what spot/zone was cleaned?

```js
vacbot.on('LastUsedAreaValues', (values) => {
    console.log('LastUsedAreaValues: ' + values);
});
vacbot.on('CurrentSpotAreas', (values) => {
    console.log('CurrentSpotAreas: ' + values);
});
vacbot.on('CurrentCustomAreaValues', (values) => {
    console.log('CurrentCustomAreaValues: ' + values);
});
```

> 
> T.i.a.!

**Comment by cactusss** [comment]
Nice, thanks that shoud work! As for the stopReason, I'll try to figure out them myself and report back.

**Comment by bhuebschen** [comment]
`{
    0: 'ERROR_NO',
    101: 'ERROR_BATTERY_LOW',
    102: 'ERROR_HANG',
    103: 'ERROR_WHEEL',
    104: 'ERROR_DOWNSENSORABNORMAL',
    105: 'ERROR_STUCK',
    106: 'ERROR_SIDEBRUSHEXAUSTED',
    107: 'ERROR_DUSTCASEHEAPEXHAUSTED',
    108: 'ERROR_SIDEABNORMAL',
    109: 'ERROR_ROLLABNORMAL',
    110: 'ERROR_NODUSTBOX',
    111: 'ERROR_BUMPABNORMAL',
    112: 'ERROR_LDSABNORMAL',
    113: 'ERROR_MAINBRUSHEXHAUSTED',
    114: 'ERROR_DUSTCASEEXHAUSTED',
    115: 'ERROR_BATTERYERROR',
    116: 'ERROR_FORWARDLOOKINGERROR',
    117: 'ERROR_GYROSCOPEERROR',
    118: 'ERROR_STRAINERBLOCK',
    119: 'ERROR_FANERROR',
    120: 'ERROR_WATERBOX_ERROR',
    121: 'ERROR_PLATE_JAMMED',
    125: 'ERROR_HARDWIPE_TANK_MACHINERY_ERROR',
    126: 'ERROR_NO_HARDWIPE_TANK',
    127: 'ERROR_NO_HARDWIPE_BRUSH',
    128: 'ERROR_SET_HARDWIPE_BRUSH',
    129: 'ERROR_BIND_HARDWIPE_BRUSH',
    201: 'ERROR_AIRFILTERUNISTALL',
    202: 'ERROR_ULTRASONICCOMPONENTABNORMAL',
    203: 'ERROR_SMALLWHEELERROR',
    204: 'ERROR_WHEEL_HANG',
    205: 'ERROR_ION_STERILIZE_EXHAUSTED',
    206: 'ERROR_ION_STERILIZE_ABNORMAL',
    207: 'ERROR_ION_STERILIZE_FAULT',
    301: 'ERROR_MCD_NO_CLEANWATER',
    302: 'ERROR_MCD_FULL_DIRTYWATER',
    303: 'ERROR_MCD_NO_CLEANWATER_TANK',
    304: 'ERROR_MCD_NO_DIRTYWATER_TANK',
    305: 'ERROR_MCD_CLEANTANK_ERROR',
    306: 'ERROR_MCD_NO_CLEANTANK_WEB',
    307: 'ERROR_MCD_MACHINERY_ERROR',
    308: 'ERROR_MCD_CONNECTION_ERROR',
    309: 'ERROR_TANK_TOOHOT_ERROR',
    601: 'ERROR_ClosedAIVISideAbnormal',
    602: 'ERROR_ClosedAIVIRollAbnormal',
}`

**Comment by cactusss** [comment]
Thanks!

**Comment by mrbungle64** [comment]
@cactusss @bhuebschen 

Does this fit so far with your devices?
For my devices it doesn't fit in every case.
For example stopReason `1` is a regular finished job.

> ```
> {
>   0: 'CLEAN_SUCCESSFUL',
>   1: 'BATTERY_LOW',
>   2: 'STOPPED_BY_APP',
>   3: 'STOPPED_BY_IR',
>   4: 'STOPPED_BY_BUTTON',
>   5: 'STOPPED_BY_WARNING',
>   6: 'STOPPED_BY_NO_DISTURB',
>   7: 'STOPPED_BY_CLEARMAP',
>   8: 'STOPPED_BY_NO_PATH',
>   9: 'STOPPED_BY_NOT_IN_MAP',
>   10: 'STOPPED_BY_VIRTUAL_WALL',
>   11: 'WIRE_CHARGING',
>   12: 'STOPPED_BY_AIR_SPOT',
>   13: 'STOPPED_BY_AIR_AUTO',
> }
> ```

**Comment by cactusss** [comment]
No, it doesn't work, or at least not for what I wanted.

**Comment by mrbungle64** [comment]
@cactusss 

> No, it doesn't work, or at least not for what I wanted.

Have you found out anything yet? It would be useful if we could collate them here.

**Comment by cactusss** [comment]
Still testing. These latest codes seem to make sense though

**Comment by vnnit** [comment]
Hi I have question, Can I save robot information and work offline but not remote api?

**Comment by mrbungle64** [comment]
@vnnit 

> Can I save robot information

no

> and work offline but not remote api?

https://github.com/bmartin5692/bumper

Btw.: Your question is Off-topic
