### ISSUE TITLE
IO Broker Warn Message

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ecovacs-deebot.js#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

i have some warnings:
<html><body>

ecovacs-deebot.0 | 2022-12-25 19:45:05.022 | warn | Error message received: Received error message: Request failed with status code 502 for command getBlock
-- | -- | -- | --
ecovacs-deebot.0 | 2022-12-25 19:41:45.847 | warn | Error message received: Received error message: Request failed with status code 502 for command getAutoEmpty
ecovacs-deebot.0 | 2022-12-25 19:41:37.627 | warn | Error message received: Received error message: Request failed with status code 502 for command getPos
ecovacs-deebot.0 | 2022-12-25 19:36:40.428 | warn | Error message received: Received error message: Request failed with status code 502 for command getBreakPoint
ecovacs-deebot.0 | 2022-12-25 19:22:53.117 | warn | Error message received: Received error message: Request failed with status code 502 for command getCleanCount

</body>
</html>

### With which model does the problem occur?

Deebot T8 series

### From which source you have installed the library?

other

### Version of the ecovacs-deebot.js library

Adapter 1.4.8

### Version of Node.js

v16.19.0

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
i see it today in the logs and i don't know how it is coming...?
in my mobile android app is no message or warning.
have you any solutions to fix the warning?
the robot is also cleaning and do his job every day.
```

**Comment by mrbungle64** [comment]
Hi @rebel1985 

in the ioBroker Repository already exists an issue for the warning messages:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/412

I have also already posted some information about this on the ioBroker forum:
https://forum.iobroker.net/post/914656

Btw.: You have created this issue in the wrong repository again 🙄
