### ISSUE TITLE
GetCleanLog serving old logs

### ISSUE THREAD

**Issue by cactusss** [mrbungle64/ecovacs-deebot.js#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I've writen an app that uses the GetCleanLogs function but it seems I can only run it once. Each time I run it again it produces the same JSON. If I restart the app it will give me e new log with the latest cleaning actions.

### With which model does the problem occur?

Deebot T9 series

### From which source you have installed the library?

GitHub

### Version of the ecovacs-deebot.js library

0.9.1

### Version of Node.js

v16

### Operating system

Linux

### Anything in the logs that might be useful?

```js
this.vacbot.on("CleanReport", (status) => {
	let oldStatus = this.getCapabilityValue('current_clean');
	this.setCapabilityValue('current_clean', status);

	if (oldStatus !== status) {
		this.log("Received a new CleanReport: " + status + " (" + oldStatus + ")");
		if (status == "idle" && oldStatus !=='init') {
			this.log('Getting CleanLogs')
			this.vacbot.run('GetCleanLogs');
		}
	}
});

this.vacbot.on('CleanLog', async (object) => {
	this.log('New CleanLog: ' + JSON.stringify(object[0]));
	this.log(JSON.stringify(object));
});
```

### Additional information

I run this code on a Homey Pro. I cleaned up the code a bit, but basically it run the GetCleanLogs after a CleanReport states the Deebot is idle.

Even if I wait for a few hours, or run several cleaning actions, a GetCleanLogs will give me the same JSON, untill I restart the app that is...

Edit: If I edit the setInterval loop from your example\app2.js file, and include the GetCleanLogs to fetch the log every 60 seconds it also fails, that is btw running on node v18.12.1

**Comment by mrbungle64** [comment]
@cactusss 

I don't own a T9 based model so I cannot check it myself, but as far as I know from the feedback it's working ...

Since version 0.9.1-alpha.4 there's a new method to get the cleaning logs for T9 based models, because Ecovacs changed the API with the T9 or N8 series:
https://github.com/mrbungle64/ecovacs-deebot.js/blob/f8a6ac775f9129102d374f764a8e94b2e5853f9b/library/vacBot.js#L1028

You may want to check this yourself if this is maybe broken...

**Comment by cactusss** [comment]
Okay, I'll see if I can figure out what is going on.

**Comment by mrbungle64** [comment]
@cactusss 

> The problem appears to be in the handleCleanLogs function; after testing it seems this.cleanLog isn't 'overwriten' by the function. If I reinitialize the cleanLog (by adding the line this.cleanLog = []; as the first line of the handleCleanLogs function) the problem seems solved.

I don't think that it is a real problem. Maybe the `handleCleanLogs` function needs to be refactored, but I don't think that this is a real problem or a bug...

> Each time I run it again it produces the same JSON.

Are you sure that it's really producing the same JSON? Have you also checked the last element(s) in the array?

**Comment by cactusss** [comment]
@mrbungle64

> Are you sure that it's really producing the same JSON?

Yes, I'm very sure; I did a full compare of the JSON contents.

> Have you also checked the last element(s) in the array?

Yes I did. The last element is always the oldest; it sorted by timestamp descending, and always returns only 20 element. A new element isn't inserted (on top) nor is it added (below).

I didn't test enough to see where it goes wrong exactly, but I'm sure that by adding the `this.cleanLog = [];` I now always get the 20 newest elements, and that is sufficient for my project; I need the newest cleanlog element (cleanLog[0]) and that works now.

I saw there was a GetLastCleanLog which might just do what I need but that is not working on my sites. Maybe it only works with other models?

**Comment by mrbungle64** [comment]
@cactusss 

> Yes, I'm very sure; I did a full compare of the JSON contents.

Maybe this is related to the new implementation for the T9 based models.

> ... but I'm sure that by adding the this.cleanLog = []; I now always get the 20 newest elements, ...

I'll add `this.cleanLog = [];` later, because it's either way ok to do it.

> I saw there was a GetLastCleanLog which might just do what I need but that is not working on my sites. Maybe it only works with other models?

Yes maybe, I'll check it this evening

**Comment by cactusss** [comment]
Excelent! Thanks for al your work on this. Could do my project without this.

**Comment by mrbungle64** [comment]
@cactusss 

You can try the [refactoring-debug-logging](https://github.com/mrbungle64/ecovacs-deebot.js/tree/refactoring-debug-logging) branch if you like.
I added `this.cleanLog = [];` and I also improved the logging output (especially when using `NODE_ENV=dev`)
Maybe you want to give me some feedback 😉 

> I saw there was a GetLastCleanLog which might just do what I need but that is not working on my sites. Maybe it only works with other models?

I had to remove this command because it also doesn't work at all. As far as I remember this command worked for a different API only and it has not had any extended benefit.

**Comment by cactusss** [comment]
@mrbungle64 

Yup, that works. A *lot* is being logged. That way I found there is a lot more settings /functions that are not on the 'shortcut functions' page :)

Again, great work! You have a paypall account?

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Yup, that works. A _lot_ is being logged. That way I found there is a lot more settings /functions that are not on the 'shortcut functions' page :)

Great 👍🏻 

> 
> Again, great work! You have a paypall account?

It's ok, thank you. I am happy when I receive positive feedback and more projects are created using this library 😃
