### ISSUE TITLE
vacbot.disconnect();

### ISSUE THREAD

**Issue by cactusss** [mrbungle64/ecovacs-deebot.js#282]
### The question

I was hoping vacbot.disconnect() would make my device disconnect from the MQTT client. But it doesn't seem to do so. Consequence if this is that when I delete a device in my app, I get some errors because messages emitted by the MQTT library are still coming in, but the device that should act on them doesn't exist anymore.

Any hint son how to solve this?

### Which model do you own?

Deebot T9 series

**Comment by mrbungle64** [comment]
@cactusss 

You're right. The client is only disconnected, but not unsubscribed.
I'll try to fix it today.

**Comment by cactusss** [comment]
🙏🏻Thanks, It would help me a lot

**Comment by mrbungle64** [comment]
@cactusss 

Please try 0.9.2-alpha.3

If it's still not properly try also `await vacbot.disconnectAsync()` instead of `vacbot.disconnect()`

**Comment by cactusss** [comment]
Had to use the `await vacbot.disconnectAsync()` but so far it seems to do the job. Again, muchas gracias!

**Comment by mrbungle64** [comment]
@cactusss 

There are 4 places in your code where you connect to the API (`EcoVacsAPI.connect()`) and 2 places where you execute `vacbot.connect()`... Are you sure that this is necessary and correct in all cases?

In my tests there were no messages coming in after executing `vacbot.disconnectAsync()`

**Comment by cactusss** [comment]
I didn't look at (it's inherited code) yet.

After looking I can find two (session handlers for login and devices) to the EcoVacsAPI in driver.js, but only one vacbot.connect in the device.js....

Please ignore the .homeybuild folder, I'v put it in the .gitignore file.

**Comment by mrbungle64** [comment]
@cactusss 

Why are you doing this?

```js
this.vacbot.disconnect();
await this.vacbot.disconnectAsync();
```

**Comment by cactusss** [comment]
It was a test :)

But I think I found the cause of the problem.

There was a loop that ran a `robot.run('GetBatteryState')` and a `robot.run('GetCleanState')` command (not sure why it was implemented that way) in the device.js. I guess that re-connected the vacbot. After removing those commands the `vacbot.disconnect()` seems to work properly.

I'm going to test ti see if without the loop everythings keep working, not sure if it was there as a keep alive, although I can't imagine that is needed.

I'll of course let you know the outcome. Thanks for the hints.

**Comment by mrbungle64** [comment]
@cactusss 

Please make sure that there are no loops running Get (or even worse Set) commands.
There are some reports that Ecovacs temporary locks out users when causing too many API calls.

**Comment by cactusss** [comment]
Thanks. Glad i caught it then!

**Comment by mrbungle64** [comment]
> After removing those commands the vacbot.disconnect() seems to work properly.

I think we can close this issue. If you still receive messages after disconnecting you can open the issue again.

**Comment by Aybert59** [comment]
> It was a test :)
> 
> But I think I found the cause of the problem.
> 
> There was a loop that ran a `robot.run('GetBatteryState')` and a `robot.run('GetCleanState')` command (not sure why it was implemented that way) in the device.js. I guess that re-connected the vacbot. After removing those commands the `vacbot.disconnect()` seems to work properly.
> 
> I'm going to test ti see if without the loop everythings keep working, not sure if it was there as a keep alive, although I can't imagine that is needed.
> 
> I'll of course let you know the outcome. Thanks for the hints.

Hello there
First thank you for all your great work
These loops were just there in order to keep in sync some status indicators. Of course managing this through the appropriate events is more convenient.
Any time you have a question on my code do not search for some hidden good reason, but rather start from the statement that i'm not an expert developer ;-)
Olivier

**Comment by cactusss** [comment]
> Hello there First thank you for all your great work These loops were just there in order to keep in sync some status indicators. Of course managing this through the appropriate events is more convenient. Any time you have a question on my code do not search for some hidden good reason, but rather start from the statement that i'm not an expert developer ;-) Olivier

Hey, don't downtalk yourself :) You did the hard part, I just added some features. I'm a hobbyist myself, copy/past is one of my best skills 😂

**Comment by cactusss** [comment]
@mrbungle64

Just found there is a problem with 0.9.2-alpha.3; there is something wrong with the either MapSpotArea or the MapSpotAreaInfo module. I'm not getting the right information.

I need to test further (hope to find the time this week) to see what goes wrong exactly.

Don't release it 😉

**Comment by mrbungle64** [comment]
@cactusss 

> Just found there is a problem with 0.9.2-alpha.3; there is something wrong with the either MapSpotArea or the MapSpotAreaInfo module. I'm not getting the right information.

Are you sure? I haven't changed anything in the MapSpotArea or MapSpotAreaInfo module ...

I'm using the 0.9.2-alpha.3 in my productive environment (ioBroker) and I haven't recognized any problems yet.

> I need to test further (hope to find the time this week) to see what goes wrong exactly.

Have you made any changes to your code that may be causing this?
Have you already pushed all your recent changes to your GitHub repo?

**Comment by cactusss** [comment]
No, I wasn't sure. But I couldn't figure out what was going wrong. So I reverted to Oliviers version on Github, to rule out any errors on my part. I tried to back-track what I did with this project, but without the changes of my own.

Olieviers github version is using ApiVersion 0.7.2 and runs fine.
I ran "npm install ecovacs-deebot@0.8.1", so now it's running ApiVersion 0.8.1 and it still runs fine.
I ran "npm install ecovacs-deebot@0.9.1", so now it's running ApiVersion 0.9.1 and it's broken.
I ran "npm install ecovacs-deebot@0.8.1" again, so now it's running ApiVersion 0.8.1 and it still runs fine again.
I ran "npm install ecovacs-deebot@0.9.0", so now it's running ApiVersion 0.9.0, and it's broken again
I ran "npm install ecovacs-deebot@0.8.3", so now it's running ApiVersion 0.8.3 and it still runs fine again.

Something in the 0.9.0 build must have been changed imho, specificaly in the GetSpotAreaInfo function. I think the problem lies there but I'm not 100% sure.

I need more time to debug this further, this is all I can offer right now.

**Comment by mrbungle64** [comment]
@cactusss 

> Olieviers github version is using ApiVersion 0.7.2 and runs fine.
> I ran "npm install ecovacs-deebot@0.8.1", so now it's running ApiVersion 0.8.1 and it still runs fine.
> I ran "npm install ecovacs-deebot@0.9.1", so now it's running ApiVersion 0.9.1 and it's broken.
> I ran "npm install ecovacs-deebot@0.8.1" again, so now it's running ApiVersion 0.8.1 and it still runs fine again.
> I ran "npm install ecovacs-deebot@0.9.0", so now it's running ApiVersion 0.9.0, and it's broken again
> I ran "npm install ecovacs-deebot@0.8.3", so now it's running ApiVersion 0.8.3 and it still runs fine again.

What exactly is broken?

**Comment by mrbungle64** [comment]
@cactusss 

Version 0.9.0 had a breaking change:
"Breaking change: Bump minimum required version of Node.js to 14.x"
What version of Node.js are you using?

**Comment by mrbungle64** [comment]
@cactusss 

If your app also not working with version 0.9.0 the issue seem to be in your app or your environment.
Version 0.9.0 was already released Nov 24, 2022
Stable version 1.4.8 of my ioBroker adapter runs with version 0.9.0-beta.2 with no reported issues.

**Comment by cactusss** [comment]
> @cactusss
> 
> Version 0.9.0 had a breaking change: "Breaking change: Bump minimum required version of Node.js to 14.x" What version of Node.js are you using?
> 
> Edit: I checked some issues created from you. It seems that you're using version 16.x

According to the release nodes of an earlier firmware version Homey is running node v16:
`Homey v7.4.1
[Core] Update Homey Apps to run in Node.js v16 environment`

When I look at the app process I get these versions:
`versions: {
    node: '16.14.2',
    v8: '9.4.146.24-node.20',
    uv: '1.43.0',
    zlib: '1.2.11',
    brotli: '1.0.9',
    ares: '1.18.1',
    modules: '93',
    nghttp2: '1.45.1',
    napi: '8',
    llhttp: '6.0.4',
    openssl: '1.1.1n+quic',
    cldr: '40.0',
    icu: '70.1',
    tz: '2021a3',
    unicode: '14.0',
    ngtcp2: '0.1.0-DEV',
    nghttp3: '0.1
`
So I guess the node.js version shouldn't be a problem

**Comment by mrbungle64** [comment]
> > @cactusss
> > Version 0.9.0 had a breaking change: "Breaking change: Bump minimum required version of Node.js to 14.x" What version of Node.js are you using?
> > Edit: I checked some issues created from you. It seems that you're using version 16.x
> 
> According to the release nodes of an earlier firmware version Homey is running node v16: `Homey v7.4.1 [Core] Update Homey Apps to run in Node.js v16 environment`
> 
> When I look at the app process I get these versions: `versions: { node: '16.14.2', v8: '9.4.146.24-node.20', uv: '1.43.0', zlib: '1.2.11', brotli: '1.0.9', ares: '1.18.1', modules: '93', nghttp2: '1.45.1', napi: '8', llhttp: '6.0.4', openssl: '1.1.1n+quic', cldr: '40.0', icu: '70.1', tz: '2021a3', unicode: '14.0', ngtcp2: '0.1.0-DEV', nghttp3: '0.1 ` So I guess the node.js version shouldn't be a problem

Yes, I already mentioned that:

"Edit: I checked some issues created from you. It seems that you're using version 16.x"

**Comment by mrbungle64** [comment]
@cactusss 

You haven't told me what exactly is broken ...

**Comment by cactusss** [comment]
> @cactusss
> 
> You haven't told me what exactly is broken ...

I was still investigating 😉

On 0.8.3 the command `this.vacbot.run('GetSpotAreaInfo', 1110814285,2);` triggers the `vacbot.on('MapSpotAreaInfo', (area).... <cut off>` command which serves me a JSON with the spotinfo.
On 0.9.0 the same command doesn't trigger the on MapSpotAreaInfo event. Even when I use this

`this.vacbot.on('MapSpotAreaInfo', (area) => { console.log('Wazzup?') });`

Nothing happens, it just doesn't gets fired.

That's what I have now. Only difference in the code is Api v0.8.3 vs Api v0.9.0

Thanks for you time btw, I understand this is hard for you to try and solve, but I don't have a clue on how to handle this myself.

**Comment by cactusss** [comment]
[0.8.3.txt](https://github.com/mrbungle64/ecovacs-deebot.js/files/10387569/0.8.3.txt)
[0.9.0.txt](https://github.com/mrbungle64/ecovacs-deebot.js/files/10387570/0.9.0.txt)
[device.js.txt](https://github.com/mrbungle64/ecovacs-deebot.js/files/10387574/device.js.txt)

The output from the two Api versions, and the js file being used

**Comment by mrbungle64** [comment]
@cactusss 

Thanks for the information.
I can see the difference from the output, but this is a very odd behavior I think.
I haven't change anything between 0.8.3 and 0.9.0 that should cause this.
In my projects I don't have this issue and I haven't heard of any such issues with other projects either...

I guess we'll have to take a closer look at your code...

**Comment by cactusss** [comment]
@mrbungle64 

It's working again. @Aybert59 hinted to the --no-optional and that seems to have done did the trick.
After running 
`npm install --omit=dev --omit=optional ecovacs-deebot@0.9.1-alpha.3`
everything seems workiung again.

Sorry for the inconvenience, and thanks for your patience.

**Comment by mrbungle64** [comment]
@cactusss 

> @mrbungle64
> 
> It's working again. @Aybert59 hinted to the --no-optional and that seems to have done did the trick. After running `npm install --omit=dev --omit=optional ecovacs-deebot@0.9.1-alpha.3` everything seems workiung again.
> 
> Sorry for the inconvenience, and thanks for your patience.

That means that the canvas module is causing that problems ...
