### ISSUE TITLE
Request failed with status code 502/504

### ISSUE THREAD

**Issue by cactusss** [mrbungle64/ecovacs-deebot.js#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I sometimes see a `command  getMapSet` being issues, but no `got response for 'getMapSet'` coming in. 

I do see an
`warn  received error event with code '-1' and message 'Received error message: Request failed with status code 502 for command getMapSet'`

Any idea what is causing this, and how to solve this? I see 502 errors on other commands coming in to:

`warn  received error event with code '-1' and message 'Received error message: Request failed with status code 502 for command getSpeed'`
`error  error sending command: Request failed with status code 502`
`warn  received error event with code '-1' and message 'Received error message: Request failed with status code 502 for command getCleanInfo'`
`error  error sending command: Request failed with status code 502`
`warn  received error event with code '-1' and message 'Received error message: Request failed with status code 502 for command getMapSet'`
`error  error sending command: Request failed with status code 502`

### With which model does the problem occur?

Deebot T9 series

### From which source you have installed the library?

GitHub

### Version of the ecovacs-deebot.js library

0.9.2-beta.0

### Version of Node.js

16+

### Operating system

Other

### Anything in the logs that might be useful?

```txt
The problem is not occuring on my own system, but with one of the Homey users that ia also running a T9+. The problem is resulting is missing all rooms from a floor.

Hope I make sense, and you know what might be going on. If needed I could update to the stable (non-beta) 0.9.2 but I didn't see any changes that would obviously are connected to this problem.
TIA
```

**Comment by mrbungle64** [comment]
@cactusss 

To get rid of the 502/504 errors please bump the library version to 0.9.3-beta.0.
I switched to a different API endpoint with version 0.9.3

**Comment by cactusss** [comment]
Will try that, and let you know if that solved the problem, Thanks for your quick answer!

**Comment by cactusss** [comment]
The problem seems solved by this. Thanks again.
