### ISSUE TITLE
No error event fired for "Charging dock not found"

### ISSUE THREAD

**Issue by noneisland** [mrbungle64/ecovacs-deebot.js#312]
When the robot encountered the problem "Charging dock not found", there's no error event fired. 

I can hear the robot voice for the error message and I can get the error in the app, but there's no error event fired.

I have a yeedi robot. 

Other error events seem to able to fire without any issue.

**Comment by mrbungle64** [comment]
@noneisland 

Is there really no event fired?
In this case it should still fire an "ErrorCode" and also an "Error" with "unknown errorCode: [errorCode]".

But I don't know if it's different for yeedi robots ...

**Comment by mrbungle64** [comment]
@noneisland 

You can try the debug output of this library:
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps

**Comment by noneisland** [comment]
I already tried app2.js, but no error messages when the error occurred.

**Comment by mrbungle64** [comment]
> I already tried app2.js, but no error messages when the error occurred.

Also in debug mode?

```
NODE_ENV=dev node ./app2.js
```

**Comment by noneisland** [comment]
I found the problem.

It is unhandled event. 

onEvt { code: 1026 }

It appears that you can just emit the event under case 'Evt' in ecovacsMQTT_JSON.js.

**Comment by mrbungle64** [comment]
@noneisland 

I added the event code to the eventCodes dictionary.
