### ISSUE TITLE
Shortcut Command to remove current Map or Restore Map Backup ???

### ISSUE THREAD

**Issue by tantai251295** [mrbungle64/ecovacs-deebot.js#367]
### The question

When I get my map to Home Assistant, it error map because mixed previous map and new map. 

What command to remove current map or restore backup map ???

<img width="498" alt="Screenshot 2023-07-26 at 15 13 09" src="https://github.com/mrbungle64/ecovacs-deebot.js/assets/70562867/1c616fdb-cdc1-4650-966b-7e9fd430e1d0">
<img width="594" alt="Screenshot 2023-07-26 at 15 17 10" src="https://github.com/mrbungle64/ecovacs-deebot.js/assets/70562867/44c5c71d-5942-44db-b6cb-13ac1f23f78f">

### Which model do you own?

Deebot T9 series

**Comment by mrbungle64** [comment]
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/388
