### ISSUE TITLE
Handle correct continent discovery

### ISSUE THREAD

**Issue by nicoduj** [mrbungle64/ecovacs-deebot.js#39]
I have one user in AU that have a problem (nicoduj/homebridge-deebotEcovacs#20) : I think there is no server for this continent (https://portal-oc.ecouser.net) . I am thinking about defaulting automatically in such case to ww server, but could be handled in my lib or in yours, what do you think ?

A simple way to do this woud be to put WW in country.js for such cases ...

I think we should stick to this :

CH: msg.ecouser.net
TW, MY, JP, SG, TH, HK, IN, KR: msg-as.ecouser.net
US: msg-na.ecouser.net
FR, ES, UK, NO, MX, DE, PT, CH, AU, IT, NL, SE, BE, DK: msg-eu.ecouser.net
Any other country: msg-ww.ecouser.net

**Comment by mrbungle64** [comment]
> I think we should stick to this :
> 
> CH: msg.ecouser.net
> TW, MY, JP, SG, TH, HK, IN, KR: msg-as.ecouser.net
> US: msg-na.ecouser.net
> FR, ES, UK, NO, MX, DE, PT, CH, AU, IT, NL, SE, BE, DK: msg-eu.ecouser.net
> Any other country: msg-ww.ecouser.net

Are you sure that this is correct?
"MX" and "AU" = "eu"?

**Comment by nicoduj** [comment]
That is what was mentioned on python repo https://github.com/wpietri/sucks/blob/master/protocol.md#location

**Comment by mrbungle64** [comment]
> That is what was mentioned on python repo https://github.com/wpietri/sucks/blob/master/protocol.md#location

I doubt that this info is correct, because it's very unlikely that Mexico ("MX") and Australia ("AU") are handled by the eu servers.

In this issue you also mentioned that there is no Ecovacs Server for "AU":
https://github.com/nicoduj/homebridge-deebotEcovacs/issues/20#issuecomment-626288447
I agree with what you metioned, because I assume that AU is also handled by "ww" servers.

Btw.: Switzerland ("CH") is confirmed working with "eu" servers ;)

**Comment by nicoduj** [comment]
Use in au tried on eu server (French country) and it worked but I agree it is strange. Maybe we should default to ww where we are not sure

**Comment by nicoduj** [comment]
Had no reports of issue since latest version, so I I am closing this for the moment :)

**Comment by razodactyl** [comment]
I'm here because I'm in `AU` and ran into this issue.
Switching to `FR` fixed my login issue as `portal-oc.ecouser.net` doesn't resolve.
