### ISSUE TITLE
Retrieve values for air quality returns code 500

### ISSUE THREAD

**Issue by p08dev** [mrbungle64/ecovacs-deebot.js#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

The command returns the following error:
`{"type":"LastError","value":{"error":"Request Timeout (command 'getAirQuality')","code":"500"}}`

<img width="981" alt="Screenshot 2023-11-22 at 09 26 18" src="https://github.com/mrbungle64/ecovacs-deebot.js/assets/8152667/2bb90d4b-4e25-4376-b687-55ab393713f5">

### With which model does the problem occur?

Other model (Please fill out the fields at the bottom of the form)

### From which source you have installed the library?

GitHub

### Version of the ecovacs-deebot.js library

0.9.5

### Version of Node.js

Node-RED 16.0.2

### Operating system

Linux

### Additional information

Airbot Z1

**Comment by mrbungle64** [comment]
@p08dev 

I will try to reproduce this issue when I receive my Airbot Z1 at the end of next week.

**Comment by mrbungle64** [comment]
@p08dev 

Please try version 0.4.10 😉

**Comment by bhuebschen** [comment]
looks like ecovacs has changed some commands.. they send "getAirQuality0" instead of "getAirQuality" from the app

**Comment by mrbungle64** [comment]
Hey @bhuebschen 

> looks like ecovacs has changed some commands.. they send "getAirQuality0" instead of "getAirQuality" from the app

Did you recognize it using mitmproxy?

**Comment by bhuebschen** [comment]
i saw it last time i was looking for the problem... but now it's gone 😂

```
{
    "app": {
        "id": "ecovacs"
    },
    "auth": {
        "realm": "ecouser.net",
        "resource": "***",
        "token": "***",
        "userid": "***",
        "with": "users"
    },
    "cmdName": "getAirQuality",
    "payload": {
        "body": {
            "data": {}
        },
        "header": {
            "pri": 1,
            "ts": "***",
            "tzm": ***,
            "ver": "0.0.50"
        }
    },
    "payloadType": "j",
    "td": "q",
    "toId": "***",
    "toRes": "***",
    "toType": "sdp1y1"
}
```

is currently sent from the App
