### ISSUE TITLE
NOOB instructions.

### ISSUE THREAD

**Issue by Rynotastic** [mrbungle64/ecovacs-deebot.js#42]
Just wondering if anyone can outline how to impliment this after installing. Only used to npm and using the config ui.

Cheers

**Comment by mrbungle64** [comment]
Hi @Rynotastic 

> Just wondering if anyone can outline how to impliment this after installing. 

Do you want to implement another software project using this library or just want to control your bot?

> Only used to npm and using the config ui.

What does "config ui" mean in this context?

**Comment by Rynotastic** [comment]
Thanks for the quick reply. To add context I am looking to control my bot in homebridge. The Control ui is a plug-in for easier configuration. Hope this helps.

**Comment by mrbungle64** [comment]
https://github.com/nicoduj/homebridge-deebotEcovacs

This is a plugin for controlling your deebot debot through HomeBridge.

**Comment by mrbungle64** [comment]
> 
> https://github.com/nicoduj/homebridge-deebotEcovacs
> 
> This is a plugin based on ecovacs-deebot.js for controlling your Deebot robot through HomeBridge.

@Rynotastic
Does this match what you were looking for?

**Comment by Rynotastic** [comment]
Fantastic! Thank you. Was unaware it was based on this project. Thanks again for taking the time to help.
