### ISSUE TITLE
is it support R96?

### ISSUE THREAD

**Issue by mraksoll4** [mrbungle64/ecovacs-deebot.js#438]
### The question

is it support Deebot R96? ( model with self cleaning )

### Which model do you own?

Other model

**Comment by mrbungle64** [comment]
@mraksoll4 

I don't think so. I never heard of this model before and it's also not listed in the dictionary of Deebot models returned by the Ecovacs API.

**Comment by mrbungle64** [comment]
@mraksoll4 

If you can add the Deebot R96 to the current Ecovacs Home App you can still try if it's working with the library, but the model is too old to support it.

**Comment by mraksoll4** [comment]
it work at app , and there exist R96 and latter models what looks the same only diferent bak  -  at latter models bak is have batary and can be used as portable vakum cleaner with batery.

Perhaps this model has different names and housings but is the same, builds a map with lidar and has the functionality of manual control and virtual walls etc.
