### ISSUE TITLE
Add DEEBOT R95MK2

### ISSUE THREAD

**Issue by bertreb** [mrbungle64/ecovacs-deebot.js#44]
Since the commit 'added modelName and imageURL' on 6 may, devices not listed in ecovacsConstants.js  cause an error. Until that update the r95mk2 worked with the lib.
Is it possible to add the DEEBOT R95MK2. The device info is:
class: 113
company:  eco-legacy

**Comment by mrbungle64** [comment]
Hi @bertreb 

I'll look at it later to provide a fix

**Comment by bertreb** [comment]
Thanks for the fix, a good solution. I tested it and it works without errors.

**Comment by mrbungle64** [comment]
@bertreb 

I published a new version on npm
