### ISSUE TITLE
Make canvas installation optional

### ISSUE THREAD

**Issue by m7r** [mrbungle64/ecovacs-deebot.js#46]
Some use cases don‘t use a visible map. For example Homebridge Integration or your example files.

I would suggest to remove canvas from the dependencies and change the code that the rendering is only done if canvas is installed manually.

**Comment by mrbungle64** [comment]
Hi @m7r,

I understand that some models do not have map features and that some use cases do not use them, but apart from installation, are there any benefits?

**Comment by m7r** [comment]
The installation of canvas is not easy on all platforms and often you have to include a hole build system just to install your node module. On space limited SoC used in home automation this could be a real burden.

Homebridge for example has a UI to install plugins. This will fail with missing canvas dependencies. Even if canvas is never used.

**Comment by mrbungle64** [comment]
@m7r 
I just removed canvas from the dependencies and made some code changes for it.

Would it be possible for you to try the latest version from GitHub?

**Comment by mrbungle64** [comment]
I have also just released version 0.4.20 on npm
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.20
