### ISSUE TITLE
BatteryLevel NaN%

### ISSUE THREAD

**Issue by cagnulein** [mrbungle64/ecovacs-deebot.js#47]
I have strange behaviour with my 2 Deebot (905, 605), after these lines, it hangs.

<pre>
$ node app.js
Device ID: xxxxxx
Account ID: xxxxxx
Encrypted account ID: xxxxxx
Password hash: xxxxx
Encrypted password hash: xxxxxxx
Country: IT
Continent: EU
Connected!
Vacbot ready
Clean status: undefined
Clean status: auto
Battery level: NaN%
Charge status: idle
Clean status: auto
Charge status: returning
Clean status: undefined
Clean status: stop
</pre>

**Comment by mrbungle64** [comment]
Please try with `app2.js`

`app.js` is deprecated. I'll delete this file ;)

**Comment by cagnulein** [comment]
better but not OK either

<pre>
$ node app2.js
eu
{ did: 'xxxxx,
  name: 'xxxxx',
  class: 'dl8fht',
  resource: '2M2m',
  nick: 'Gina',
  company: 'eco-ng',
  bindTs: 1570385440359 }
[app2.js] isKnownDevice: true
[app2.js] isSupportedDevice: false
[app2.js] name: DEEBOT 600 Series
[app2.js] hasMainBrush: true
[app2.js] hasSpotAreas: false
[app2.js] hasCustomAreas: false
[app2.js] hasMoppingSystem: true
[app2.js] hasVoiceReports: true
vacbot ready
[app2.js] CleanReport: undefined
[app2.js] Error: unknown errorCode: NoError
[app2.js] CleanReport: auto
[app2.js] main_brush: 31
[app2.js] Error: Request Timeout
[app2.js] BatteryInfo: 97
[app2.js] ChargeState: idle
[app2.js] CleanReport: auto
[app2.js] water level: 2
[app2.js] BatteryInfo: 97

</pre>

**Comment by mrbungle64** [comment]
> better but not OK either
> 

Why not OK?

**Comment by cagnulein** [comment]
[app2.js] Error: unknown errorCode: NoError

**Comment by mrbungle64** [comment]
> [app2.js] Error: unknown errorCode: NoError

NoError = no error

**Comment by cagnulein** [comment]
hah ok :)
