### ISSUE TITLE
Deebot 600 works great so far

### ISSUE THREAD

**Issue by alanmcg** [mrbungle64/ecovacs-deebot.js#50]
Not tested all features but so far I'm able to get status info and send some commands for Deebot 600.

**Comment by mrbungle64** [comment]
Hi @alanmcg 

thanks for you feedback :+1: 
I moved the Deebot 600 to the "are known to work" list.

**Comment by alanmcg** [comment]
Thanks, but actually you moved the 601 :) It is only the 600 that I have tested.

**Comment by mrbungle64** [comment]
> ... It is only the 600 that I have tested.

Yes, I know. I have not made the commit of this change yet. The Deebot 601 was already on that list :)
