### ISSUE TITLE
Amount of movement left/right

### ISSUE THREAD

**Issue by houdang** [mrbungle64/ecovacs-deebot.js#51]
Hey everybody,
does someone know "how much" does a move left or right actually turn the device?
My Deebot Slim 2 turns like 400° when i trigger a onetime "moveleft".

I also tried to find out something through the code or documentation but it seems we only send a XML with the option "left" or "right" to move. Is that true? Wireshark doesnt work for me as the app sends all requests encrypted (or im doing something wrong....)

Is there any debug mode with which i can enable the envLog messages ?

Thanks!

PS: That's actually not an issue and might be wrong here, feel free to close it

**Comment by mrbungle64** [comment]
> Hey everybody,

Hi @houdang 

> does someone know "how much" does a move left or right actually turn the device?

I have not been thinking about this yet ;)

> My Deebot Slim 2 turns like 400° when i trigger a onetime "moveleft".
> 
> I also tried to find out something through the code or documentation but it seems we only send a XML with the option "left" or "right" to move. Is that true? Wireshark doesnt work for me as the app sends all requests encrypted (or im doing something wrong....)

Yes, this is correct :)

> 
> Is there any debug mode with which i can enable the envLog messages ?

Yes, by setting the `NODE_ENV` environment variable to `dev`

```bash
NODE_ENV=dev node app2.js
```

> 
> Thanks!

You are welcome! :)

> 
> PS: That's actually not an issue and might be wrong here, feel free to close it

**Comment by houdang** [comment]
Thanks for the feedback Sascha. 
What i'm wondering is that I can trigger the deebot to turn left a little or more depending on how long i touch the button in the app. But the API call "left" or "right" turns completely like 360/400°, even if i call stop etc..

I might wonder if there's another API call existing in the ecovacs universe - but hard to find out with documentation and encrypted traffic :-(

I will gonna dig into it deeper, let's see what i can find out

Thanks !
