### ISSUE TITLE
Rooms Area 0-14

### ISSUE THREAD

**Issue by davefr90** [mrbungle64/ecovacs-deebot.js#57]
'0': {"en": "Default  (A, B, C...)", "de": "Standard (A, B, C...)"},
    '1': {"en": "Living room", "de": "Wohnzimmer"},
    '2': {"en": "Dining room", "de": "Esszimmer"},
    '3': {"en": "Bedroom", "de": "Schlafzimmer"},
    '4': {"en": "Study", "de": "Büro"},
    '5': {"en": "Kitchen", "de": "Küche"},
    '6': {"en": "Bathroom", "de": "Badezimmer"},
    '7': {"en": "Laundry", "de": "Waschküche"},
    '8': {"en": "Lounge", "de": "Lounge"},
    '9': {"en": "Storeroom", "de": "Lagerraum"},
    '10': {"en": "Kids room", "de": "Kinderzimmer"},
    '11': {"en": "Sunroom", "de": "Wintergarten"},
    '12': {"en": "Corridor", "de": "Flur"},
    '13': {"en": "Balcony", "de": "Balkon"},
    '14': {"en": "Gym", "de": "Fitnessstudio"}

**Comment by boriswerner** [comment]
@davefr90 is there anything missing or incorrect? The new rooms were already added with commit e140f2a9c53aa6d2f6f4eb59389f1f641a8be052.
