### ISSUE TITLE
How to set number of cleanings to 2 for custom area?

### ISSUE THREAD

**Issue by MichaelPlank** [mrbungle64/ecovacs-deebot.js#58]
Hi team,
is it possible to set the number of cleanings for a custom area to 2 instead of a single cleaning in the config?

so far I have:
`
 "publishCustomAreaSwitches": [
                "1600,6700,4500,10400"
            ]
`

Thx for this awesome plugin!!! @ #

**Comment by mrbungle64** [comment]
Hi @MichaelPlank 

this question to [homebridge-deebotecovacs](https://github.com/nicoduj/homebridge-deebotEcovacs) Plugin, right? ;)

**Comment by mrbungle64** [comment]
You can follow the link [here](https://github.com/nicoduj/homebridge-deebotEcovacs/issues/new) to create an issue for homebridge-deebotecovacs

**Comment by MichaelPlank** [comment]
Ah ok, sorry, I will post the question there. Thx!
