### ISSUE TITLE
Feature request to set adv. parameters such as "Auto Empty"

### ISSUE THREAD

**Issue by Boehmer86** [mrbungle64/ecovacs-deebot.js#63]
**Quick note upfront**
I just want to say that it is awesome work you are doing here for the community, thanks a lot and well done!

**Describe the solution you'd like**
I would like to be able to set advanced parameters like "auto empty" to "on/off". I want to do so that I can create HomeKit rules which turn "auto empty" off after 8pm and on again after 8am. It is very noisy but also sometimes in the evening I need the support of my Ozmo to help me clean the kitchen after cooking. Being able to set this function would allow me to both call for a cleanup and keep peace with they neighbours.

I sniffed the communication the of my Ozmo to learn all my map coordinates for my custom areas. At the same time I found how the advanced parameter are set and read. It looks quite straight forward to me, so my hope is that you may be able to add them to the library so I can lobby for a push towards HomeBridge. Alternatively, maybe there is a way for you to implement a general parameter function. Something where the user can input advanced parameters to be set so that you do not always need to update the library. Something like: set.custom_parameter("setAutoEmpty","enable",1)

As follows the capture I did:
`{"toType":"fqxoiu","payloadType":"j","toRes":"1Ar1","payload":{"header":{"pri":1,"tzm":60,"ts":"1613246868815","ver":"0.0.50"},"body":{"data":{"enable":0}}},"td":"q","toId":"42______________","cmdName":"setAutoEmpty","auth":{"token":"3d8_______________5757","resource":"IOS842F8B0G9","userid":"_____________","with":"users","realm":"ecouser.net"}}`

As I can see, once you toggle it obviously just flips the "enable" bit.
If you want I can do captures for all the advanced settings my Ozmo T8+ exposes. 

I am also happy to help implementing them. I don't lack the programming skills but sadly mostly the time and focus needed. I am very happy to donate here for this library and support the work happening. It would be great if you could enable the sponsor/donate function for your project on GitHub. It would be a great way to give back for the work and effort you put in.

**Deebot model** (please complete the following information):
 - Model name: "Deebot Ozmo T8+"
 - Usage via HomeBridge/HomeKit with the Ecovacs Deebot Plugin by @nicoduj 

With many greetings from Berlin,

Robert

**Comment by mrbungle64** [comment]
@Boehmer86 

> I just want to say that it is awesome work you are doing here for the community, thanks a lot and well done!

Thank you for the feedback and detailed information 👍🏻 

I already started to implement the `setAutoEmpty` and `getAutoEmpty` commands.

Can you please try if it's already working?

1.)

```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2.)

Please edit `app2.js`
* Email/Ecovacs ID, password and country code
* Add the following lines:

```js
vacbot.on('AutoEmpty', (value) => {
    console.log('[app2.js] AutoEmpty: ' + value);
});
```

```js
let autoEmpty = 1; // Please also try 0
vacbot.run('getAutoEmpty');
vacbot.run('setAutoEmpty', autoEmpty);
```

3.)
```bash
NODE_ENV=dev node app2.js | grep -E 'AutoEmpty|autoEmpty'
```

**Comment by mrbungle64** [comment]
@Boehmer86 

> I am also happy to help implementing them. I don't lack the programming skills but sadly mostly the time and focus needed. I am very happy to donate here for this library and support the work happening. It would be great if you could enable the sponsor/donate function for your project on GitHub. It would be a great way to give back for the work and effort you put in.

I'm still not sure if I want to enable the sponsor/donate function but you're welcome to join working on this project 😉 
It would then be easier to implement functions for the T8 series, since I do not own such a device.

**Comment by Boehmer86** [comment]
Thanks @mrbungle64 for the extremely swift reply on a Sunday.
In short, your changes worked – well done!

I can confirm that setting the value to 0 disables "AutoEmpty" both as a matter of fact as well as within the official App. Setting it to 1, enables "AutoEmpty" respectively.

As follows if needed/helpful the log output.

With setting "0":
`root@mr38-homebridge:~/scripts/deebot/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'AutoEmpty|autoEmpty'
[VacBot] action: getAutoEmpty
[VacBot] Sending command `getAutoEmpty`
[EcovacsMQTT_JSON] c: {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"____","userid":"___","with":"users"},"cmdName":"getAutoEmpty","payload":{"header":{"pri":"2","ts":1613327564143,"tmz":480,"ver":"0.0.22"},"body":{"data":{"id":"___"}}},"payloadType":"j","td":"q","toId":"_______","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] Sending {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"_____","userid":"_____","with":"users"},"cmdName":"getAutoEmpty","payload":{"header":{"pri":"2","ts":1613327564143,"tmz":480,"ver":"0.0.22"},"body":{"data":{"id":"_____"}}},"payloadType":"j","td":"q","toId":"_______","toRes":"1Ar1","toType":"fqxoiu"}
[VacBot] action: setAutoEmpty
[VacBot] Sending command `setAutoEmpty`
[EcovacsMQTT_JSON] c: {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"_____","userid":"____","with":"users"},"cmdName":"setAutoEmpty","payload":{"header":{"pri":"2","ts":1613327564149,"tmz":480,"ver":"0.0.22"},"body":{"data":{"enable":0,"id":"51158180"}}},"payloadType":"j","td":"q","toId":"_____","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] Sending {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"____","userid":"el4vzgw0f3735ffa","with":"users"},"cmdName":"setAutoEmpty","payload":{"header":{"pri":"2","ts":1613327564149,"tmz":480,"ver":"0.0.22"},"body":{"data":{"enable":0,"id":"51158180"}}},"payloadType":"j","td":"q","toId":"______","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] _handle_command_response() command: setAutoEmpty
[EcovacsMQTT_JSON] _handle_command_response() resp(0): setAutoEmpty {"header":{"pri":1,"tzm":480,"ts":"1613327562864","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok"}}
[EcovacsMQTT_JSON] _handle_message topic: setAutoEmpty
[EcovacsMQTT_JSON] _message_to_dict eventName: setAutoEmpty
[EcovacsMQTT_JSON] _handle_command() command setAutoEmpty received event: {"resultCode":0,"resultCodeMessage":"ok"}
[EcovacsMQTT_JSON] _handle_command_response() command: getAutoEmpty
[EcovacsMQTT_JSON] _handle_command_response() resp(0): getAutoEmpty {"header":{"pri":1,"tzm":480,"ts":"1613327563342","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"code":0,"msg":"OK","data":{"status":0,"enable":0}}}
[EcovacsMQTT_JSON] _handle_message topic: getAutoEmpty
[EcovacsMQTT_JSON] _message_to_dict eventName: getAutoEmpty
[EcovacsMQTT_JSON] _handle_command() command getAutoEmpty received event: {"resultCode":0,"resultCodeMessage":"OK","resultData":{"status":0,"enable":0}}
[VacBot] *** autoEmpty = 0
[app2.js] AutoEmpty: 0
^C`

With setting it to "1":
`root@mr38-homebridge:~/scripts/deebot/ecovacs-deebot.js/example# NODE_ENV=dev node app2.js | grep -E 'AutoEmpty|autoEmpty'
[VacBot] action: getAutoEmpty
[VacBot] Sending command `getAutoEmpty`
[EcovacsMQTT_JSON] c: {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"__","userid":"_","with":"users"},"cmdName":"getAutoEmpty","payload":{"header":{"pri":"2","ts":1613327906758,"tmz":480,"ver":"0.0.22"},"body":{"data":{"id":"_"}}},"payloadType":"j","td":"q","toId":"_","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] Sending {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"_","userid":"_","with":"users"},"cmdName":"getAutoEmpty","payload":{"header":{"pri":"2","ts":1613327906758,"tmz":480,"ver":"0.0.22"},"body":{"data":{"id":"83075309"}}},"payloadType":"j","td":"q","toId":"_","toRes":"1Ar1","toType":"fqxoiu"}
[VacBot] action: setAutoEmpty
[VacBot] Sending command `setAutoEmpty`
[EcovacsMQTT_JSON] c: {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"_","userid":"_","with":"users"},"cmdName":"setAutoEmpty","payload":{"header":{"pri":"2","ts":1613327906763,"tmz":480,"ver":"0.0.22"},"body":{"data":{"enable":1,"id":"42859849"}}},"payloadType":"j","td":"q","toId":"_","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] Sending {"auth":{"realm":"ecouser.net","resource":"129f77ea","token":"_","userid":"_","with":"users"},"cmdName":"setAutoEmpty","payload":{"header":{"pri":"2","ts":1613327906763,"tmz":480,"ver":"0.0.22"},"body":{"data":{"enable":1,"id":"42859849"}}},"payloadType":"j","td":"q","toId":"_","toRes":"1Ar1","toType":"fqxoiu"}
[EcovacsMQTT_JSON] _handle_command_response() command: getAutoEmpty
[EcovacsMQTT_JSON] _handle_command_response() resp(0): getAutoEmpty {"header":{"pri":1,"tzm":480,"ts":"1613327905667","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"code":0,"msg":"OK","data":{"status":0,"enable":0}}}
[EcovacsMQTT_JSON] _handle_message topic: getAutoEmpty
[EcovacsMQTT_JSON] _message_to_dict eventName: getAutoEmpty
[EcovacsMQTT_JSON] _handle_command() command getAutoEmpty received event: {"resultCode":0,"resultCodeMessage":"OK","resultData":{"status":0,"enable":0}}
[VacBot] *** autoEmpty = 0
[EcovacsMQTT_JSON] _handle_command_response() command: setAutoEmpty
[EcovacsMQTT_JSON] _handle_command_response() resp(0): setAutoEmpty {"header":{"pri":1,"tzm":480,"ts":"1613327905704","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok"}}
[EcovacsMQTT_JSON] _handle_message topic: setAutoEmpty
[EcovacsMQTT_JSON] _message_to_dict eventName: setAutoEmpty
[EcovacsMQTT_JSON] _handle_command() command setAutoEmpty received event: {"resultCode":0,"resultCodeMessage":"ok"}
^C`

**Comment by Boehmer86** [comment]
@mrbungle64 to reply to your second post:
I am both happy to sponsor and support the development.

I am very happy to add the other functions the same way you added AutoEmpty. It might be good to get a short note from your on where to implement it. I can also reverse it by seeing your final commit. However as being new some short guidance is welcome. Also is it possible for me to edit the Wiki? It would be nice to add a note towards the customArea feature to explain how to get the coordinates. Silly asked, is there a simpler way than using the  "HTTPCatcher" App?

To list all available advanced functions of the T8+ that I could add:
- AutoBoost suction (enabled by default; boosting suction levels automatically depending on the floor, works quite well)
- Auto-Empty (enabled by default; empties the dust bin after returning-to-charge; very noisy)
- TrueDetect 3D Obstacle Avoidance (enabled by default; iirc/not guaranteed use of lira + camera)
- Continuous Cleaning (disabled by default; if not finished within one charge, do a short charge and finish work)
- Do Not Disturb (disabled by default; accepts time-range input; disabled all lights and all schedule within the time window)
- Cleaning cloth reminder (disabled by default; accepts minutes 10-60; reminds you to change the mopping mop)

Best, Robert

**Comment by mrbungle64** [comment]
@Boehmer86 
> @mrbungle64 to reply to your second post:
> I am both happy to sponsor and support the development.

Hi Robert,

I'm glad to hear that my change is already working and that you want to support this project 😄 

> 
> I am very happy to add the other functions the same way you added AutoEmpty. It might be good to get a short note from your on where to implement it. I can also reverse it by seeing your final commit. However as being new some short guidance is welcome.

Have you already taken a look at my commit? https://github.com/mrbungle64/ecovacs-deebot.js/commit/bb04150c2d98b8ab640ed686c899eff378ece8b6
But it also depends on how Ecovacs implements the other commands.

> Also is it possible for me to edit the Wiki?

As far as I know only repository collaborators are allowed to edit the wiki. It is also possible to make it public but that's not a good idea I guess 😉 

> It would be nice to add a note towards the customArea feature to explain how to get the coordinates. Silly asked, is there a simpler way than using the "HTTPCatcher" App?

You can use the example app and start a custom area cleaning using the mobile app. You should get an ouput like this:

```
[EcovacsMQTT_JSON] LastUsedAreaValues: -4498.000000,-1935.000000,-2814.000000,-3412.000000
```

> 
> To list all available advanced functions of the T8+ that I could add:
> 
> * AutoBoost suction (enabled by default; boosting suction levels automatically depending on the floor, works quite well)
> * Auto-Empty (enabled by default; empties the dust bin after returning-to-charge; very noisy)
> * TrueDetect 3D Obstacle Avoidance (enabled by default; iirc/not guaranteed use of lira + camera)
> * Continuous Cleaning (disabled by default; if not finished within one charge, do a short charge and finish work)
> * Do Not Disturb (disabled by default; accepts time-range input; disabled all lights and all schedule within the time window)
> * Cleaning cloth reminder (disabled by default; accepts minutes 10-60; reminds you to change the mopping mop)

That sounds good 👍🏻 
"Continuous cleaning" and "Do not disturb" are already implemented, but unfortunately I didn't get it working for 950 type models (920/950/T8) yet. You can take a look at the `GetOnOff`/`SetOnOff` commands. Maybe you can get it working 😉 

> 
> Best, Robert

**Comment by Boehmer86** [comment]
Hello @mrbungle64 

To report, I know hacked together two simple scripts, one which disables all sounds and auto-empty and one which sets the volume to level one and enables auto-empty again. Using HomeKit automations I set it so it is disabled at night and enabled in the morning again. I did several test and so far it seems to work quite well!

I achieved what I wanted to do when I opened this ticket earlier this morning. It's really cool and I am quite happy. Thanks a lot again! You also likely get anonymously kudos from my neighbours who are no longer experiencing nightly dust-bin shrieks ;-)

I also reviewed and now better understood the changes you made. I should have looked for the commit right away, it was a bit obvious. Thanks also for the note re the example App, it's a nice trick to do the CustomAreas this way. Please add this to the Wiki, at least I remember not having understood this earlier. I am also happy to do packet sniffing but this is very likely much easier for the average user.

I will let this now run for the week and see how it goes. Likely by the weekend I will have time again to dig in again and then I will see if I can add the other functions/fix them. At least I can give it a shot.

Many greetings

Robert

**Comment by mrbungle64** [comment]
@Boehmer86 

> ... Please add this to the Wiki, at least I remember not having understood this earlier. I am also happy to do packet sniffing but this is very likely much easier for the average user.

https://github.com/mrbungle64/ecovacs-deebot.js/wiki/CustomArea#retrieve-coordinates-from-log-output

Many greetings
Sascha
