### ISSUE TITLE
control bugs iobroker

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ecovacs-deebot.js#64]
**Software version** (please complete the following information):
- Library version: 
- Source:  "npm", 7.5.3
- Node.js version:  10.23.3
- Operating system: raspian
- Hardware: Raspberry Pi 4

**Deebot model** (please complete the following information):
 - Model name: [e.g. "Deebot Ozmo 950"]
 - Deebot ozmo 900

**Describe the bug**
control problem with deebot 900
vor 3-6 wochen oder so ging alles über den adapter wunderbar mittlerweile oft probleme

**Additional context**
kann starten aber nicht stoppen, mehrfach den adapter neu gestartet, und auch neu angemeldet

**Comment by mrbungle64** [comment]
@rebel1985 

Bitte [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/new/choose) einen Issue erstellen 😉 
Das hier ist die Library.

Es fehlen auch noch Infos zur eingesetzten Adapter Version und es ist nicht ganz eindeutig ob eine eine Deebot 900 oder Deebot OZMO 900 ist. Ich meine mich daran erinnern zu können, dass Du einen OZMO hast.
