### ISSUE TITLE
Communicate with deebot to write new firmware/Change region?

### ISSUE THREAD

**Issue by sasha935** [mrbungle64/ecovacs-deebot.js#67]
Is there a way to change the Deebot's region conf? 

I have a Chinese bot that I prefer to change to EU since moving. Thinking either need to flash with EU firmware or simply change a line from CN to EU on the bot.

**Comment by mrbungle64** [comment]
@sasha935 

> Thinking either need to flash with EU firmware

I have never heard of anyone successfully flashing firmware to an Ecovacs Deebot vacuum cleaner.

>  or simply change a line from CN to EU on the bot.

What line do you mean?
