### ISSUE TITLE
Behandlung von Infos beim Deebot Ozmo 950

### ISSUE THREAD

**Issue by mrbungle64** [mrbungle64/ecovacs-deebot.js#7]
@boriswerner

Ich vermutete mal stark, dass von den Infos aktuell beim Ozmo 950 nur 'batteryinfo' und 'cleanreport' funktionieren, weil das noch über die `_body_data_to_command` Methode behandelt wird.
Eigentlich sollte die separate Behandlung für den 950 in der `_dict_to_command` Methode überflüssig sein.

```javascript
        if (json.hasOwnProperty('body')) {
            return this._body_data_to_command(json['body']['data']);
        }
```

Mein Vorschlag wäre, dass wir das erst mal umkehren in der `dict_to_command` Methode:

```javascript
    _dict_to_command(json) {
       // Das hier sollte eigentlich inzwischen immer funktionieren
        if (json['event']) {
            return json['event'];
        }
       // Ggf. notwendig ein paar andere Modelle, die wir beide nicht besitzen
        if (json.hasOwnProperty('ctl')) {
            return json['ctl'];
        }
       // Fallback für den Ozmo 950. Sollte aber eigentlich nicht mehr notwendig sein
        if (json.hasOwnProperty('body')) {
            return this._body_data_to_command(json['body']['data']);
        }
    }
```

Falls das (besser) funktioniert können wir den Fallback und damit auch die `_body_data_to_command` rauswerfen. Du hattest das ja auch schon mal kurz angemerkt meine ich mich zu erinnern ;)

**Comment by boriswerner** [comment]
> if (json['event']) {
            return json['event'];
}

Wird glaube ich beim 950 derzeit auch nicht funktionieren, da es kein Event im Json gibt und du topic nicht korrekt übersetzt wird.
Ich bin da auch gerade dran (deswegen das erweiterte logging im letzten pull), würde das aber erst in den größeren Umbau einfließen lassen.

**Comment by mrbungle64** [comment]
@boriswerner 

ok, dann baue ich jetzt erst mal einen Release auf der aktuellen Grundlage.

**Comment by boriswerner** [comment]
Das könnte man dann auch gut in iobroker Forum unter der Kategorie "Tester" dann einstellen um Feedback einzusammeln.
Bist du da auch aktiv? Da kann man nämlich auch Direktnachrichten schicken... Ich bin da unter meinem GitHub Account zu finden.

**Comment by mrbungle64** [comment]
> @boriswerner
> 
> ok, dann baue ich jetzt erst mal einen Release auf der aktuellen Grundlage.

@boriswerner 

Hast Du gerade die Möglichkeit den aktuellen Stand von Github kurz zu testen?
Falls der mit dem Ozmo 950 keine neuen Probleme macht würde ich einen npm Release bauen und den in den ioBroker Adapter verwenden und auch den mal so releasen.

**Comment by mrbungle64** [comment]
> Das könnte man dann auch gut in iobroker Forum unter der Kategorie "Tester" dann einstellen um Feedback einzusammeln.

Ja das werde ich dann in den nächsten Tagen mal angehen.

> Bist du da auch aktiv? Da kann man nämlich auch Direktnachrichten schicken... Ich bin da unter meinem GitHub Account zu finden.

Ich habe dort einen Account - bin aber bisher noch nicht wirklich aktiv.

**Comment by boriswerner** [comment]
> Hast Du gerade die Möglichkeit den aktuellen Stand von Github kurz zu testen?
> Falls der mit dem Ozmo 950 keine neuen Probleme macht würde ich einen npm Release bauen und den in den ioBroker Adapter verwenden und auch den mal so releasen.

Läuft alles wie erwartet. (auch aus dem iobroker, hab die library da manuell aktualisiert).
Soll ich sonst mal einen Aufruf zum Test des Adapters im Forum speziell für den 950 machen?

**Comment by mrbungle64** [comment]
> > Hast Du gerade die Möglichkeit den aktuellen Stand von Github kurz zu testen?
> > Falls der mit dem Ozmo 950 keine neuen Probleme macht würde ich einen npm Release bauen und den in den ioBroker Adapter verwenden und auch den mal so releasen.
> 
> Läuft alles wie erwartet. (auch aus dem iobroker, hab die library da manuell aktualisiert).

@boriswerner 
ok, danke. Adapter Release ist über Github verfügbar :)

> Soll ich sonst mal einen Aufruf zum Test des Adapters im Forum speziell für den 950 machen?

Ich denke wir sollten das nicht separat machen.

**Comment by mrbungle64** [comment]
> > Hast Du gerade die Möglichkeit den aktuellen Stand von Github kurz zu testen?
> > Falls der mit dem Ozmo 950 keine neuen Probleme macht würde ich einen npm Release bauen und den in den ioBroker Adapter verwenden und auch den mal so releasen.
> 
> Läuft alles wie erwartet. (auch aus dem iobroker, hab die library da manuell aktualisiert).
> Soll ich sonst mal einen Aufruf zum Test des Adapters im Forum speziell für den 950 machen?

@boriswerner 
Ich bin gerade dabei einen Text für den Aufruf zum Test des Adapters zu verfassen.
Ich schicke Dir den Entwurf dann später zu. Wird aber ggf. erst morgen Abend soweit sein.

**Comment by boriswerner** [comment]
folgendes funktioniert nun:
consumables.filter
consumables.main_brush
consumables.side_brush
control.waterLevel (der wird einmalig aktualisiert und wird dann rot, weil er nicht bestätigt ist, ist das normal?)
history.dateOfLastStateChange
history.timestampOfLastStateChange
history*
info.battery

history.* außer den StateChange zeigen die anderen nichts, wie funktionieren die?
info.chargestatus zeigt nichts an, sollte mit dem neuen Pull aber auch gehen
info.cleanstatus zeigt nur unknown, sollte mit dem neuen Pull aber auch gehen
info.deviceStatus zeigt nichts an (was macht der?)
info.error zeigt nichts an (hatte aber auch keinen Fehler...)

**Comment by mrbungle64** [comment]
@boriswerner 
> folgendes funktioniert nun:
> consumables.filter
> consumables.main_brush
> consumables.side_brush
> control.waterLevel (der wird einmalig aktualisiert und wird dann rot, weil er nicht bestätigt ist, ist das normal?)

Bedeutet "einmalig", dass es quasi nur 1x bis zum nächsten Adapter Neustart funktioniert?
Bei mir funktoniert es beliebig oft - ich muss halt in der Mobile app - beim Überprüfen ob es funktoniert hat - die View immer neu aufrufen, damit es auch angezeigt wird.
Dass es rot wird, ist im Moment noch normal, da es wie Du schon sagst nicht bestätigt wird. Aber damit bin ich auch noch nicht glücklich.

> history.dateOfLastStateChange
> history.timestampOfLastStateChange
> history*
> info.battery

Das hört sich ja in der Summe schon mal gut an :+1: 

> 
> history.* außer den StateChange zeigen die anderen nichts, wie funktionieren die?

StateChange berücksichtigt alle Statusänderungen außerhalb von "history"
die anderen nur jeweils einen speziellen
- StartCharging bei ChargeState
- StartCleaning bei CleanReport

> info.chargestatus zeigt nichts an, sollte mit dem neuen Pull aber auch gehen
> info.cleanstatus zeigt nur unknown, sollte mit dem neuen Pull aber auch gehen

Damit sollten dann die Werte in "history" auch funktionieren

> info.deviceStatus zeigt nichts an (was macht der?)

Der sollte anzeigen, in welchem Zustand sich der Bot gerade befindet:
`stopped`, `paused`, `cleaning`

Das ist aber alles (vor allem das unter "history") nicht in Stein gemeißelt - k.A. ob das irgendwer was mit anfangen kann ;)
Ich nehme da gerne Anregungen und Verbesserungsvorschläge entgegen.

> info.error zeigt nichts an (hatte aber auch keinen Fehler...)

Ja das zeigt noch nicht viel an und man sollte da mal eine Trennung machen zwischen Fehlerzuständen aus ioBroker und den vom Gerät selbst bzw. von dem was die Ecovacs API meldet.
