### ISSUE TITLE
Unhandled error when MQTT doesn't return JSON

### ISSUE THREAD

**Issue by glennvgastel** [mrbungle64/ecovacs-deebot.js#76]
**Software version**
- Library version: current master

**Deebot model**
 - Model name: All

**Describe the bug**
When there is a server issue on Ecovac's side, `JSON.parse()` will fail with a SyntaxError since the returned data is HTML.
That causes an unhandled exception, that can't easily be caught by the client.

I'd suggest adding a try-catch block around the parse and rejecting with a specific error.

**Additional context**
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/library/ecovacsMQTT.js#L103

**Comment by mrbungle64** [comment]
Hi @glennvgastel 

Please try the latest version of the current master.
I [added](https://github.com/mrbungle64/ecovacs-deebot.js/commit/a5d142aea9395bdfc614dcc1bcae2ef24ac2be95) new a error code: `'-3': 'Error parsing response data'` so that you can handle the error via the error events.

**Comment by glennvgastel** [comment]
That works great - thanks for the quick fix!
