### ISSUE TITLE
GetSpotAreaInfo reports cryptical string instead of coordinates (T9+)

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/ecovacs-deebot.js#78]
When running "GetSpotAreaInfo" agains T9+ I receive some cryptical string like `XQAABADVAAAAAByMgwBkPYS7zQalrYrx1hSCG6giOMQsI8RjfOqNPi/yv49O7npECj9XhQHcda+Bs+xFFuP2O4kWhbncYiQYD5rxILTROXPRdDfURxZJVwG66EoA` for `mapSpotAreaBoundaries`. Similar output in app2.js but followed by error `callEcovacsDeviceAPI failed for cmd getMapSubSet: TypeError: Cannot read property 'find' of null`.

Expected value would be something similar to the value shown in Wiki page of "Map Data"

**Comment by mrbungle64** [comment]
@unclej84 

Do you still experience this issue?

**Comment by unclej84** [comment]
Yes, this is also included in the MapDataObject which was added recently.

**Comment by mrbungle64** [comment]
@unclej84 

Is this also the case with `GetVirtualBoundaryInfo`?

**Comment by unclej84** [comment]
Currently I have no boundaries added yet. I can try tomorrow and report back on it.

**Comment by mrbungle64** [comment]
@unclej84 

What do you receive when executing

```bash
NODE_ENV=dev node app2.js | grep 'command getMapSubSet received event'
```

**Comment by unclej84** [comment]
Shall I post the output here or send via email? There is a key `"compress":1` - so I guess the coordinates are compressed because of many edges (`"totalCount":102` and `"valueSize":1107`). The value looks like this: `"value":"XQAABABTBAAAABaMwwFhWAzxtflZ/TcO7+3F7rx2UKKAxaLnHA2r9OPsdv1f2+fWcma6h9/MizBsXFayew9xCYeak2jcFR9JfXrRVbimkjmPCTgcKYsvAdbWQrDdP4lpAqQCMKxG1p1XjxS+IQZkcW6AZQdXsHnHlWbp/XRy5I8L8kZ3w01MLflvY2RS0fQgm5fiSMC3MNF3urjMyQJFTTQmr6EpB2ZZAaLo29tR9rGE3KS/hdZ23avufH1Zfk1NQB6D+6yfL/IHBwmo/XxBrUeAXsSB73OrdmG38w51frojp5lE0LYODg7nuRsXhxGzM65IvxjLSGZyO9DPbMiNI77xrY5yqM0W2+oQeS1MrwW69eg="`

**Comment by mrbungle64** [comment]
@unclej84 

It seems that they switched to compressed data because of the higher detail resolution and 3D data ...

**Comment by unclej84** [comment]
is it only for my series or did they do in general? Could this be handled by the compress key to decide if the data can be passed directly or needs to be uncompressed? Do you have any idea how to uncompress it?

**Comment by mrbungle64** [comment]
> is it only for my series or did they do in general?

For OZMO 920, 930 and Deebot 901 it's still uncompressed. I suspect it may be just for the T9 series or maybe some of the other latest models.

> Could this be handled by the compress key to decide if the data can be passed directly or needs to be uncompressed?
> Do you have any idea how to uncompress it?

Not yet 😅

**Comment by boriswerner** [comment]
> @unclej84 
> 
> What do you receive when executing
> 
> ```bash
> NODE_ENV=dev node app2.js | grep 'command getMapSubSet received event'
> ```

The full output of that command would be good. (Make sure there are no username/password/token Infos included but I think the should be avoided by the grep. Can't test it myself tonight and @mrbungle64  is much better at those grep commands than me ;-) )

**Comment by unclej84** [comment]
hope it helps
[output2.log](https://github.com/mrbungle64/ecovacs-deebot.js/files/6454053/output2.log)

**Comment by boriswerner** [comment]
Looks good. Will do a more detailed check tomorrow.

**Comment by mrbungle64** [comment]
@unclej84 

Please try the latest version from GitHub to see if it works with it.

cc: @boriswerner

**Comment by unclej84** [comment]
Tested and works great - I can draw a X-Y-plot with the coordinates and it is similar to the map in the app
