### ISSUE TITLE
SupportedDevices und KnownDevices

### ISSUE THREAD

**Issue by mrbungle64** [mrbungle64/ecovacs-deebot.js#8]
In der Datei `library/ecovacsConstants.js` hatte ich begonnen die 'SupportedDevices' und 'KnownDevices' zu registrieren.

Kriterium für 'SupportedDevices' war für mich, dass Entwickler Zugriff auf diese Modelle haben und diese direkt supporten können (bis vor ein paar Tagen war ich das ja alleine mit meinen 2 Geräten).
Bei 'KnownDevices' hatte ich die Modelle aufgenommen, deren Eigenschaften ich kannte.

Der Aufbau ist aktuell ja folgender (trifft auf beides zu):
```javascript
   deviceClass: {
        "name": string,
        "main_brush": boolean,
        "spot_area": boolean,
        "custom_area": boolean,
        "mopping_system": boolean,
        "voice_report": boolean,
        'single_room': boolean
    }
```

Hintergrund war, dass ich die Objekte im ioBroker Adapter (falls sinnvoll) abhängig vom Modell erstellen möchte.

Fragen:
- Gibt es aktuell Verbesserungsvorschläge?
- Gibt es Eigenschaften, welche hier noch aufgenommen werden sollten?
- Wollen wir bei 'SupportedDevices' nun den Ozmo 950 aufnehmen?

**Comment by boriswerner** [comment]
Die Übersicht von https://github.com/bmartin5692/bumper/blob/master/bumper/models.py
Hast du ja auch schon drin, vielleicht sollte man das zusammenführen (unter supporttypes?)
Ansonsten reicht das glaube ich. Man könnte noch nach Clean Modes etc unterscheiden aber das muss wohl nicht.
Eigenschaften;
Beim 950 gibt es zb noch mulitimap Support.
Spot cleaning wird ggf wieder interessant, wenn es beim 950 tatsächlich auch geht.
Sonst fällt mir spontan nix ein.
Ich würde den 950 als supported ansehen :-)
