### ISSUE TITLE
Improve LifeSpan event

### ISSUE THREAD

**Issue by mrbungle64** [mrbungle64/ecovacs-deebot.js#83]
See [here](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot/issues/2)

**Comment by mrbungle64** [comment]
@dbochicchio 

I replaced `LifeSpanStats` with `LifeSpan` event.
Please use `GetLifeSpan` (without any further argument) to retrieve [structured event](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Events#lifespan).

**Comment by edenhaus** [comment]
It is possible to get all components stats from a single request.

> The "problem" is that you have to request each type separately, but in the case of MQTT/JSON type models, the library outputs all values that are already available.

This is not correct. You can put multiple components in the list. See [here](https://github.com/edenhaus/Deebotozmo/blob/f1a58e9bb36bd09b97c8ebc890b976506ee7b093/deebotozmo/commands.py#L131)

**Comment by mrbungle64** [comment]
> It is possible to get all components stats from a single request.
> 
> > The "problem" is that you have to request each type separately, but in the case of MQTT/JSON type models, the library outputs all values that are already available.
> 
> This is not correct. You can put multiple components in the list. See [here](https://github.com/edenhaus/Deebotozmo/blob/f1a58e9bb36bd09b97c8ebc890b976506ee7b093/deebotozmo/commands.py#L131)

@edenhaus 
Thanks for the information 👍🏻
