### ISSUE TITLE
Combined element ChargingPosition - wrong object

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/ecovacs-deebot.js#85]
The ChargingPosition event returns an object with the coordinates of the charging station but the object contains the position of the robot. Is this the intended output?

![image](https://user-images.githubusercontent.com/60842330/118363676-c6808c80-b595-11eb-9cac-88f34ec50719.png)

**Comment by mrbungle64** [comment]
@unclej84 

Fixed with latest version from GitHub.
