### ISSUE TITLE
Combined Event "MoppingSystemInfo" - shall "enabled" be the same as "WaterBoxInfo"

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/ecovacs-deebot.js#86]
I like the new "MoppingSystemInfo" and wanted to remove the event listeners for the node-red node for single events. Does the key "enabled" the value from "WaterBoxInfo" (Integer) as bool?

**Comment by mrbungle64** [comment]
> Does the key "enabled" the value from "WaterBoxInfo" (Integer) as bool?

Yes exactly
