### ISSUE TITLE
currentSpotAreaID returns "void" for T9

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/ecovacs-deebot.js#87]
Just noticed that "currentSpotAreaID" and "spotAreaID" in "Position" return void instead of ID.

![image](https://user-images.githubusercontent.com/60842330/118364104-5410ac00-b597-11eb-8610-afba9a54cad8.png)

**Comment by mrbungle64** [comment]
@unclej84 

The return value `void` indicates that canvas is not available.

**Comment by mrbungle64** [comment]
* `unknown` = current spot area could not be determined
* `void` = it is not possible to determine the current spot area
