### ISSUE TITLE
More complete status

### ISSUE THREAD

**Issue by dbochicchio** [mrbungle64/ecovacs-deebot.js#89]
Hi @mrbungle64,

the latest iteration of the lib has broken my code, since I was watching for *MoppingSystemInfo* to get the status, even when not mopping.

So, I'm proposing something similar to this to send a complete report of the most used variables related to status:

```
emitMoppingSystemReport() {
  var r = {
	  'cleanStatus': this.bot.cleanReport,
	  'cleanInfo': {
		  'speed': (this.bot.cleanSpeed || 0)
	  }
  };
  
  if (this.bot.hasMoppingSystem())
	  r['waterInfo'] = {
		  'enabled': Boolean(Number(this.bot.waterboxInfo || 0)),
		  'level': this.bot.waterLevel || 0
	  }
  
  this.emit("MoppingSystemInfo", r);
  }
```

The idea behind it is to carry both water info (if present) and clean info (I'm calling it from cleanspeed as well and maybe the function name is not fitting anymore). What do you think?

**Comment by mrbungle64** [comment]
Hi @dbochicchio 

> the latest iteration of the lib has broken my code, since I was watching for MoppingSystemInfo to get the status, even when not mopping.

but you agreed to my proposed change, right 🤔 
https://github.com/mrbungle64/ecovacs-deebot.js/pull/80#issuecomment-835882251

> The idea behind it is to carry both water info (if present) and clean info (I'm calling it from cleanspeed as well and maybe the function name is not fitting anymore). What do you think?

It's ok for me. I will change it later today.

**Comment by dbochicchio** [comment]
| but you agreed to my proposed change, right 🤔

you know, it looked good in theory, but then I discovered it won't work for my edge case. no problem, I'm not complaining at all. Thanks for the hard work ;)

**Comment by mrbungle64** [comment]
@dbochicchio 

Please check if this fits for your use case:

```js
emitMoppingSystemReport() {
    const vacuumPowerAdjustmentOk = !this.bot.hasVacuumPowerAdjustment() || (this.bot.cleanSpeed !== null);
    const moppingSystemOk = !this.bot.hasMoppingSystem() || (this.bot.waterLevel !== null);
    if (vacuumPowerAdjustmentOk && moppingSystemOk) {
        let r = {
            'cleanStatus': this.bot.cleanReport
        };
        if (this.bot.hasVacuumPowerAdjustment() && (this.bot.cleanSpeed !== null)) {
            r['cleanInfo'] = {
                'level': this.bot.cleanSpeed
            }
        }
        if (this.bot.hasMoppingSystem() && (this.bot.waterLevel !== null)) {
            r['waterInfo'] = {
                'enabled': Boolean(Number(this.bot.waterboxInfo || 0)),
                'level': this.bot.waterLevel
            }
        }
        this.emit("MoppingSystemInfo", r);
    }
}
```

**Comment by mrbungle64** [comment]
@dbochicchio 

I just made a commit based on my proposal from yesterday.
