### ISSUE TITLE
Add ability to toggle Advanced Mode

### ISSUE THREAD

**Issue by karlwynn** [mrbungle64/ecovacs-deebot.js#90]
**Describe the solution you want**.
Hello,
thank you very much for the time and effort you put into this project!

Everything you can do in the official ecovacs application (and more) can be done with this project,
with the exception of enabling/disabling the "advanced mode". I disable this mode before moving the deebot by hand to clean
an area that is not accessible from the charging station so that the map is not reset.
Maybe this feature is already implemented, but I couldn't find it.

**Deebot Model** (please complete the following information):
 - Model name: Deebot Ozmo 950, but I think it would work the same way on all recent models.

![advmode](https://user-images.githubusercontent.com/86469514/123406753-86a4c000-d5ab-11eb-8640-665d84b2794c.jpeg)

**Comment by mrbungle64** [comment]
Hi @karlwynn 

thanks for your feedback 👍🏻 

I just implemented the follwing Shortcut functions:
- `EnableAdvancedMode`
- `DisableAdvancedMode`
- `GetAdvancedMode`
