### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by dbochicchio** [mrbungle64/ecovacs-deebot.js#91]
Hey @mrbungle64 I've added a new Deebot 920 to my collection and I was trying to adapt my library to multi-bots and finally released it.

I'm not sure if it's me, but I've found that the library is updating only device at a given time. So, if I'm running two devices at the same time, I'm only getting notifications for one (the first one is loading, to be precise). If I ask for updates, it's working.
I'm using the same client instance.

Before giving up and finding a new route, I'm just double check-in with you. Thanks!

**Comment by mrbungle64** [comment]
Hi @dbochicchio 

> Hey @mrbungle64 I've added a new Deebot 920 to my collection and I was trying to adapt my library to multi-bots and finally released it.
> 
> I'm not sure if it's me, but I've found that the library is updating only device at a given time. So, if I'm running two devices at the same time, I'm only getting notifications for one (the first one is loading, to be precise). If I ask for updates, it's working.
> I'm using the same client instance.

you must use a separate instance and it's also helpful if it's also runnig as a seperate process.

With my [ioBroker adapter](https://github.com/mrbungle64/ioBroker.ecovacs-deebot) it works flawlessly and with my [node-RED Node](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot) it's also working with multiple devices.

> 
> Before giving up and finding a new route, I'm just double check-in with you. Thanks!

Have you already published your library?

**Comment by dbochicchio** [comment]
> you must use a separate instance and it's also helpful if it's also runnig as a seperate process.
>
> With my ioBroker adapter it works flawlessly and with my node-RED Node it's also working with multiple devices.

Thanks, I've looked at your code and know I understand why you where pointing to a single bot.

> Have you already published your library?

nope, but I think I'm ready. It's an MQTT bridge and I was just waiting to add and test support for multiple devices before releasing it. I'll fix it and release it very soon. Thanks for your help and your fantastic lib, again!
