### ISSUE TITLE
Update für Wiki-Sound-Page

### ISSUE THREAD

**Issue by benep** [mrbungle64/ecovacs-deebot.js#92]
Ich hab mal die Tabelle der Sounds im Wiki für den T8 mit den neuen Meldungen upgedated. Leider kann ich das Wiki nicht direkt bearbeiten.

[playSound.md](https://github.com/mrbungle64/ecovacs-deebot.js/files/6835117/playSound.md)

**Comment by mrbungle64** [comment]
@benep 

Vielen Dank! 👍🏻 
Ich werde den Artikel damit aktualiseren.
