### ISSUE TITLE
Pause command is not working for OZMO slim 11

### ISSUE THREAD

**Issue by yantoz** [mrbungle64/ecovacs-deebot.js#95]
**Software version** (please complete the following information):
- Library version: 0.6.1-beta.7
- Source: npm
- Node.js version: v10.16.3
- Operating system: Linux
- Hardware: Raspberry Pi 4

**Deebot model** (please complete the following information):
 - Model name: OZMO Slim 11 (reported as: DEEBOT OZMO Slim10 Series)

**Describe the bug**
Pause command is not working (returning 500: timeout)
I have a solution that works specifically for slim 11 as described below but I don't know if it would break other non 950 models.
I also don't know if this is specific to slim 11 (not affecting slim 10), so it is good if any slim 10 owner can confirm.
Any reference I could found says that slim 11 is just white version of slim 10 so technically they are the same.

**Additional context**
It works if I make modification in vacBotCommand_non950type.js

from:

```javascript
class Pause extends Clean {
    constructor() {
        super('pause', 'pause');
    }
}
```

to:

```javascript
class Pause extends Clean {
    constructor() {
        super('auto', 'pause');
    }
}
```

**Additional info**
GetCleanLogs returns empty result. I am aware this is listed as known issues for T9 series but want to add that it is also true for slim 11 (and probably slim 10 as well).
All other functionalities that I tried works, including Resume that already uses super('auto', 'resume'). Great work!

**Comment by mrbungle64** [comment]
@yantoz 

Thanks for the information 👍🏻 

> I also don't know if this is specific to slim 11 (not affecting slim 10), so it is good if any slim 10 owner can confirm.
> Any reference I could found says that slim 11 is just white version of slim 10 so technically they are the same.

Can you please check if the device class for the OZMO Slim 11 is  `02uwxm`?

```
node app2.js | grep 'class'
```

---

> ```js
> class Pause extends Clean {
>     constructor() {
>         super('auto', 'pause');
>     }
> }
> ```

I'll check if this also works for other 950 type models 👍🏻

**Comment by yantoz** [comment]
@mrbungle64 

yes, it is.

```
Devices: [{"did":"<redacted>","name":">redacted>","class":"02uwxm","resource":"PHv6","nick":"DeeBot","company":"eco-ng","bindTs":1589599294627,"service":{"jmq":"jmq-ngiot-na.dc.ww.ecouser.net","mqs":"api-ngiot.dc-na.ww.ecouser.net"}}]
```

**Comment by mrbungle64** [comment]
@yantoz 

Please try if it's working with version 0.6.1-beta.8

**Comment by yantoz** [comment]
Flawless. I see you made it specifiable as well for other cleaning modes.
Thanks. I think we can close this issue.

**Comment by mrbungle64** [comment]
@yantoz 

> Flawless.

I'm glad to hear that

> I see you made it specifiable as well for other cleaning modes.

Yes, I tested the "Pause" command with 2 non 950 type models (OZMO 930, Deebot 901), but if one of the other models not working with `auto` you can still pass `pause` as argument.

> Thanks. I think we can close this issue.
