### ISSUE TITLE
Bad South America API

### ISSUE THREAD

**Issue by juliangsibecas** [mrbungle64/ecovacs-deebot.js#98]
Hi! How it's going? 

My robot is registered in Argentina. When I wanted to use the library I found that the API does not exist (portal-sa.ecouser.net).

**Comment by mrbungle64** [comment]
Hi @juliangsibecas, thanks for your feedback.

Have you already tried if it's working with `WW` as country code?

**Comment by juliangsibecas** [comment]
It works well! 

How about changing the continents from SA to WW? Since it would not make sense to keep SA and this could be used in all cases:

`ecovacsDeebot.countries[this.config.countryCode].continent`

If it's okay with you, I'll do the PR!

**Comment by mrbungle64** [comment]
@juliangsibecas 

> If it's okay with you, I'll do the PR!

Of course that's okay with me. I would welcome that 👍🏻

**Comment by juliangsibecas** [comment]
#99
